name: afkcredits
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"
#environment:
#  sdk: ">=2.16.2 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  
  stacked: ^2.3.15
  stacked_services: ^0.9.3
  stacked_generator: ^0.7.13
  firebase_core: ^1.20.0
  cloud_firestore: ^3.4.1
  firebase_storage: ^10.3.3
  cloud_functions: ^3.3.3
  connectivity_plus: ^2.3.6
  nanoid: ^1.0.0
  map_launcher: ^2.1.2
  url_launcher: ^6.1.5
  # Firebase Authentications
  firebase_auth: ^3.5.1
  google_sign_in: ^5.4.0
  sign_in_with_apple: ^4.1.0
  #Google Map 
  google_maps_flutter: ^2.1.9

  flip_card: ^0.6.0

  geolocator: ^9.0.0

  permission_handler: ^10.0.0
  currency_text_input_formatter: ^2.1.7
  money2: ^3.1.3
  uuid: ^3.0.6
  qr_flutter: ^4.0.0
  qr_code_scanner: ^1.0.0

  stacked_firebase_auth: ^0.2.14
  flutter_signin_button: ^2.0.0
  battery_plus: ^2.1.4
  open_settings: ^2.0.2
  flutter_polyline_points: ^1.0.0
  dio: ^4.0.6
  cached_network_image: ^3.2.1
  flutter_svg: ^1.1.1+1
  get_it: ^7.2.0
  logger:
  freezed_annotation: ^2.1.0
  json_annotation: ^4.6.0
  flutter_launcher_icons: ^0.9.3
  notion_api: ^1.2.0
  device_info: ^2.0.3

  lottie: ^1.2.2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  #flutter_stripe: ^1.2.0
  #pay: ^1.0.1
  transparent_image: ^2.0.0
  flutter_secure_storage: ^5.0.2
  crypto: ^3.0.1
  persistent_bottom_nav_bar: ^4.0.2
  rxdart: ^0.27.1
  stop_watch_timer: ^1.3.1
  geoflutterfire: ^3.0.3
  location: ^4.3.0
  google_maps_flutter_web: ^0.4.0+2  
  ar_flutter_plugin: ^0.7.1
  flutter_vibrate: ^1.3.0
  slidable_button: ^2.0.0+1
  slide_to_act: ^2.0.1
  shimmer: ^2.0.0
  map_picker: ^0.0.3
  image_picker: ^0.8.4+4
  progress_indicator_button: ^0.0.3
  get: ^4.6.5
  #background_fetch: ^1.1.0
  #awesome_notifications: ^0.6.21
  awesome_notifications: #^0.7.0-beta.2
    git:
      #ref: "8d0bc27"
      ref: "a850f27"
      url: https://github.com/rafaelsetragni/awesome_notifications
  fluttertoast: ^8.0.3

  transparent_pointer: ^1.0.0
  afkcredits_ui: 
    path: ./afkcredits_ui/

  circular_menu: ^2.0.1
  pedometer: ^3.0.0
  flutter_background_service: ^2.0.0
  geopoint: ^1.0.0
  freezed: ^2.0.3+1
  update: ^0.3.1
  source_gen: ^1.2.2
  json_serializable: ^6.2.0
  flutter_dotenv: ^5.0.2
  rounded_loading_button: ^2.0.8
  bloc_test: ^9.0.1
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.1
  introduction_screen: ^3.0.1
  dotenv: ^4.0.1
  geo_firestore_flutter: ^0.1.5
  # Harguilar Ended Here 


dev_dependencies:
  flutter_test:
    sdk: flutter
  # auto_route_generator:
  stacked_generator: ^0.7.15
  freezed: ^2.1.0+1
  json_serializable: ^6.1.5
  flutter_dotenv: ^5.0.2
  rounded_loading_button: ^2.0.8
  dependency_validator: ^3.0.0

  flutter_archive: ^5.0.0

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0
  build_runner: ^2.2.0

  mockito: ^5.1.0

# icons
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/afk_credits.PNG"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/map_style.txt
    - assets/DayStyle.json
    - assets/PokemonStyle.json
    - assets/avatars/hercules-avatar.png
    - assets/avatars/hercules-avatar2.png    
    - assets/icons/
    - assets/icons/afk_credits.PNG
    - assets/icons/afk_credits_orig.png
    - assets/icons/melted-clock.png
    - assets/icons/afk_credits_small.PNG
    - assets/icons/afk_credits_small_orig.png
    - assets/icons/afk_credits_small_colored.PNG
    - assets/icons/trash_icon.svg
    - assets/icons/measure-distance.png    
    - assets/icons/magnet.png
    - assets/icons/drawing-compass.png
    - assets/icons/treasure.png
    - assets/icons/treasure2.png
    - assets/icons/treasure2_big.png
    - assets/icons/treasure_small.png
    - assets/icons/treasure-map.png
    - assets/icons/measure.png
    - assets/icons/create_quest.png
    - assets/icons/giftcard.png
    - assets/icons/money.png
    - assets/icons/qrcode.png
    - assets/icons/map.png
    - assets/icons/location-icon.ico
    - assets/icons/curve-arrow.png
    - assets/icons/cardinal-point.png  
    - assets/lottie/lottietest.json  
    - assets/icons/walk.png
    - assets/icons/run.png
    - assets/icons/person.png
    - assets/icons/computer.png
    - assets/illustrations/activity_illustration.png
    - assets/illustrations/anna_hercules_world.png
    - assets/illustrations/infographic_wallet.png
    - assets/illustrations/infographic.png
    - assets/illustrations/parents_meditate.png
    - assets/illustrations/screen_time.png
    - assets/illustrations/wallet_earning.png
    - assets/illustrations/wallet_spending.png
    - assets/illustrations/activity_illustration_with_arrows.png

  # To add assets to your application, add an assets section, like this:
  #assets:
    - .env
    - dotenv
  #- icons/sem-internet.jpg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages