/// The type of dialog to show
enum DialogType {
  Stats,
  MoneyTransfer,
  Onboarding,
  PurchaseGiftCard,
  CollectCredits,
  CheckTravelledDistance,
  CollectedMarker,
  FoundTreasure,
  EditQuestInformation,
  SuperUserSettings,
  CheckpointInArea,
  QrCodeInArea,
  PurchaseScreenTime,
  ChildStatCard,
  CreditConversionInfo,
  OnboardingDialog,
  BewareOfSurroundings,
  CustomScreenTime,
  NumberQuests,
  AvatarSelectDialog,
  ExplorerSettings,
}
