// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDokI6Bf9CtpbpRPWi0bB-1kHD7BSiGh_o',
    appId: '1:277863819591:web:1aae51eb1f4a845ba2c462',
    messagingSenderId: '277863819591',
    projectId: 'afk-credits-112d2',
    authDomain: 'afk-credits-112d2.firebaseapp.com',
    storageBucket: 'afk-credits-112d2.appspot.com',
    measurementId: 'G-RN7CY3JS49',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRuA9szk7WCz7E2xmTGQZhbCIawuRByhg',
    appId: '1:277863819591:android:32a7705d3e777e68a2c462',
    messagingSenderId: '277863819591',
    projectId: 'afk-credits-112d2',
    storageBucket: 'afk-credits-112d2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxtkPc8lV1jj86sRak6WObnIahEBRr_3c',
    appId: '1:277863819591:ios:ee5d27d2d88fdf57a2c462',
    messagingSenderId: '277863819591',
    projectId: 'afk-credits-112d2',
    storageBucket: 'afk-credits-112d2.appspot.com',
    androidClientId: '277863819591-ggl08fr70fvfbq7oena3gc5pb32gnpu9.apps.googleusercontent.com',
    iosClientId: '277863819591-fmsc15tbdn9qbprc5fn74s8lks8inr61.apps.googleusercontent.com',
    iosBundleId: 'com.afkcred',
  );
}
