// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYQLp-49Pp0q0P3YYHl0geNaFQb6Q2DNw',
    appId: '1:73058156701:android:105b6502ce9eec714ed474',
    messagingSenderId: '73058156701',
    projectId: 'afk-credits-prod',
    storageBucket: 'afk-credits-prod.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALanfdzCsxTQO5Pfd_xfkxdtXYvoBShhw',
    appId: '1:73058156701:ios:d7fa5eebfaa3af584ed474',
    messagingSenderId: '73058156701',
    projectId: 'afk-credits-prod',
    storageBucket: 'afk-credits-prod.appspot.com',
    androidClientId: '73058156701-l7s528khru9qeti8vg7iu8d1itna9oa8.apps.googleusercontent.com',
    iosClientId: '73058156701-9ukfrs09ufdpj3uvhji9qug1ha170c37.apps.googleusercontent.com',
    iosBundleId: 'com.hercules.prod',
  );
}
