// Mocks generated by Mockito 5.0.14 from annotations
// in afkcredits/test/helpers/test_helpers.dart.
// Do not manually edit this file.

import 'dart:async' as _i17;
import 'dart:ui' as _i38;

import 'package:afkcredits/apis/firestore_api.dart' as _i20;
import 'package:afkcredits/datamodels/payments/money_transfer.dart' as _i22;
import 'package:afkcredits/datamodels/payments/money_transfer_query_config.dart'
    as _i23;
import 'package:afkcredits/datamodels/quests/active_quests/activated_quest.dart'
    as _i12;
import 'package:afkcredits/datamodels/quests/markers/marker.dart' as _i13;
import 'package:afkcredits/datamodels/quests/quest.dart' as _i7;
import 'package:afkcredits/datamodels/users/favorite_places/user_fav_places.dart'
    as _i18;
import 'package:afkcredits/datamodels/users/public_info/public_user_info.dart'
    as _i21;
import 'package:afkcredits/datamodels/users/statistics/user_statistics.dart'
    as _i4;
import 'package:afkcredits/datamodels/users/user.dart' as _i3;
import 'package:afkcredits/enums/authentication_method.dart' as _i19;
import 'package:afkcredits/enums/user_role.dart' as _i16;
import 'package:afkcredits/flavor_config.dart' as _i26;
import 'package:afkcredits/services/environment_services.dart' as _i24;
import 'package:afkcredits/services/geolocation/geolocation_service.dart'
    as _i31;
import 'package:afkcredits/services/layout/layout_service.dart' as _i29;
import 'package:afkcredits/services/local_storage_service.dart' as _i27;
import 'package:afkcredits/services/markers/marker_service.dart' as _i34;
import 'package:afkcredits/services/payments/transfers_history_service.dart'
    as _i30;
import 'package:afkcredits/services/qrcodes/qrcode_service.dart' as _i35;
import 'package:afkcredits/services/quests/quest_service.dart' as _i32;
import 'package:afkcredits/services/quests/stopwatch_service.dart' as _i33;
import 'package:afkcredits/services/user_service.dart' as _i5;
import 'package:cloud_firestore/cloud_firestore.dart' as _i6;
import 'package:firebase_auth/firebase_auth.dart' as _i14;
import 'package:flutter/material.dart' as _i37;
import 'package:flutter_secure_storage/flutter_secure_storage.dart' as _i28;
import 'package:geolocator/geolocator.dart' as _i10;
import 'package:google_maps_flutter/google_maps_flutter.dart' as _i11;
import 'package:logger/logger.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:places_service/src/models/application_models.dart' as _i8;
import 'package:places_service/src/places_service.dart' as _i25;
import 'package:rxdart/rxdart.dart' as _i9;
import 'package:stacked_firebase_auth/stacked_firebase_auth.dart' as _i15;
import 'package:stacked_services/stacked_services.dart' as _i36;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeLogger_0 extends _i1.Fake implements _i2.Logger {}

class _FakeUser_1 extends _i1.Fake implements _i3.User {}

class _FakeUserStatistics_2 extends _i1.Fake implements _i4.UserStatistics {}

class _FakeAFKCreditsAuthenticationResult_3 extends _i1.Fake
    implements _i5.AFKCreditsAuthenticationResult {}

class _FakeFirebaseFirestore_4 extends _i1.Fake
    implements _i6.FirebaseFirestore {}

class _FakeDocumentReference_5 extends _i1.Fake
    implements _i6.DocumentReference {}

class _FakeQuest_6 extends _i1.Fake implements _i7.Quest {}

class _FakeCollectionReference_7 extends _i1.Fake
    implements _i6.CollectionReference {}

class _FakePlacesLocation_8 extends _i1.Fake implements _i8.PlacesLocation {}

class _FakePlacesDetails_9 extends _i1.Fake implements _i8.PlacesDetails {}

class _FakeBehaviorSubject_10<T> extends _i1.Fake
    implements _i9.BehaviorSubject<T> {}

class _FakePosition_11 extends _i1.Fake implements _i10.Position {}

class _FakeCameraPosition_12 extends _i1.Fake implements _i11.CameraPosition {}

class _FakeActivatedQuest_13 extends _i1.Fake implements _i12.ActivatedQuest {}

class _FakeMarker_14 extends _i1.Fake implements _i13.Marker {}

class _FakeFirebaseAuth_15 extends _i1.Fake implements _i14.FirebaseAuth {}

class _FakeFirebaseAuthenticationResult_16 extends _i1.Fake
    implements _i15.FirebaseAuthenticationResult {}

/// A class which mocks [UserService].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserService extends _i1.Mock implements _i5.UserService {
  @override
  _i2.Logger get log =>
      (super.noSuchMethod(Invocation.getter(#log), returnValue: _FakeLogger_0())
          as _i2.Logger);
  @override
  Map<String, _i3.User> get supportedExplorers =>
      (super.noSuchMethod(Invocation.getter(#supportedExplorers),
          returnValue: <String, _i3.User>{}) as Map<String, _i3.User>);
  @override
  set supportedExplorers(Map<String, _i3.User>? _supportedExplorers) => super
      .noSuchMethod(Invocation.setter(#supportedExplorers, _supportedExplorers),
          returnValueForMissingStub: null);
  @override
  Map<String, _i4.UserStatistics> get supportedExplorerStats =>
      (super.noSuchMethod(Invocation.getter(#supportedExplorerStats),
              returnValue: <String, _i4.UserStatistics>{})
          as Map<String, _i4.UserStatistics>);
  @override
  set supportedExplorerStats(
          Map<String, _i4.UserStatistics>? _supportedExplorerStats) =>
      super.noSuchMethod(
          Invocation.setter(#supportedExplorerStats, _supportedExplorerStats),
          returnValueForMissingStub: null);
  @override
  _i3.User get currentUser =>
      (super.noSuchMethod(Invocation.getter(#currentUser),
          returnValue: _FakeUser_1()) as _i3.User);
  @override
  _i4.UserStatistics get currentUserStats =>
      (super.noSuchMethod(Invocation.getter(#currentUserStats),
          returnValue: _FakeUserStatistics_2()) as _i4.UserStatistics);
  @override
  bool get hasLoggedInUser => (super
          .noSuchMethod(Invocation.getter(#hasLoggedInUser), returnValue: false)
      as bool);
  @override
  _i16.UserRole get getUserRole =>
      (super.noSuchMethod(Invocation.getter(#getUserRole),
          returnValue: _i16.UserRole.sponsor) as _i16.UserRole);
  @override
  bool get hasRole =>
      (super.noSuchMethod(Invocation.getter(#hasRole), returnValue: false)
          as bool);
  @override
  List<_i3.User> get supportedExplorersList =>
      (super.noSuchMethod(Invocation.getter(#supportedExplorersList),
          returnValue: <_i3.User>[]) as List<_i3.User>);
  @override
  _i17.Future<void> syncUserAccount(
          {String? uid, bool? fromLocalStorage = false}) =>
      (super.noSuchMethod(
              Invocation.method(#syncUserAccount, [],
                  {#uid: uid, #fromLocalStorage: fromLocalStorage}),
              returnValue: Future<void>.value(),
              returnValueForMissingStub: Future<void>.value())
          as _i17.Future<void>);
  @override
  _i17.Future<_i3.User> createUserAccountFromFirebaseUser(
          {_i16.UserRole? role}) =>
      (super.noSuchMethod(
              Invocation.method(
                  #createUserAccountFromFirebaseUser, [], {#role: role}),
              returnValue: Future<_i3.User>.value(_FakeUser_1()))
          as _i17.Future<_i3.User>);
  @override
  _i17.Future<_i3.User> createUserAccount({_i3.User? user}) =>
      (super.noSuchMethod(
              Invocation.method(#createUserAccount, [], {#user: user}),
              returnValue: Future<_i3.User>.value(_FakeUser_1()))
          as _i17.Future<_i3.User>);
  @override
  _i17.Future<void> createUserFavouritePlaces(
          {String? userId, _i18.UserFavPlaces? favouritePlaces}) =>
      (super.noSuchMethod(
              Invocation.method(#createUserFavouritePlaces, [],
                  {#userId: userId, #favouritePlaces: favouritePlaces}),
              returnValue: Future<void>.value(),
              returnValueForMissingStub: Future<void>.value())
          as _i17.Future<void>);
  @override
  _i17.Future<List<_i18.UserFavPlaces>?> getUserFavouritePlaces(
          {String? userId}) =>
      (super.noSuchMethod(
              Invocation.method(#getUserFavouritePlaces, [], {#userId: userId}),
              returnValue: Future<List<_i18.UserFavPlaces>?>.value())
          as _i17.Future<List<_i18.UserFavPlaces>?>);
  @override
  _i17.Future<String?> getLocallyLoggedInUserId() =>
      (super.noSuchMethod(Invocation.method(#getLocallyLoggedInUserId, []),
          returnValue: Future<String?>.value()) as _i17.Future<String?>);
  @override
  _i17.Future<_i5.AFKCreditsAuthenticationResult> runLoginLogic(
          {_i19.AuthenticationMethod? method,
          String? emailOrName,
          String? password,
          _i16.UserRole? role}) =>
      (super.noSuchMethod(
              Invocation.method(#runLoginLogic, [], {
                #method: method,
                #emailOrName: emailOrName,
                #password: password,
                #role: role
              }),
              returnValue: Future<_i5.AFKCreditsAuthenticationResult>.value(
                  _FakeAFKCreditsAuthenticationResult_3()))
          as _i17.Future<_i5.AFKCreditsAuthenticationResult>);
  @override
  _i17.Future<_i5.AFKCreditsAuthenticationResult> runCreateAccountLogic(
          {_i19.AuthenticationMethod? method,
          _i16.UserRole? role,
          String? fullName,
          String? email,
          String? password}) =>
      (super.noSuchMethod(
              Invocation.method(#runCreateAccountLogic, [], {
                #method: method,
                #role: role,
                #fullName: fullName,
                #email: email,
                #password: password
              }),
              returnValue: Future<_i5.AFKCreditsAuthenticationResult>.value(
                  _FakeAFKCreditsAuthenticationResult_3()))
          as _i17.Future<_i5.AFKCreditsAuthenticationResult>);
  @override
  bool isSupportedExplorer({String? uid}) => (super.noSuchMethod(
      Invocation.method(#isSupportedExplorer, [], {#uid: uid}),
      returnValue: false) as bool);
  @override
  _i17.Future<dynamic> createExplorerAccount(
          {String? name, String? password}) =>
      (super.noSuchMethod(
          Invocation.method(
              #createExplorerAccount, [], {#name: name, #password: password}),
          returnValue: Future<dynamic>.value()) as _i17.Future<dynamic>);
  @override
  _i17.Future<dynamic> addExplorerToSupportedExplorers({String? uid}) =>
      (super.noSuchMethod(
          Invocation.method(#addExplorerToSupportedExplorers, [], {#uid: uid}),
          returnValue: Future<dynamic>.value()) as _i17.Future<dynamic>);
  @override
  void setupUserDataListeners(
          {_i17.Completer<void>? completer, void Function()? callback}) =>
      super.noSuchMethod(
          Invocation.method(#setupUserDataListeners, [],
              {#completer: completer, #callback: callback}),
          returnValueForMissingStub: null);
  @override
  _i17.Future<void> addExplorerStatsListeners(
          {List<String>? explorerIds, void Function()? callback}) =>
      (super.noSuchMethod(
              Invocation.method(#addExplorerStatsListeners, [],
                  {#explorerIds: explorerIds, #callback: callback}),
              returnValue: Future<void>.value(),
              returnValueForMissingStub: Future<void>.value())
          as _i17.Future<void>);
  @override
  _i17.Future<dynamic> addExplorerStatListener(
          {String? explorerId, void Function()? callback}) =>
      (super.noSuchMethod(
          Invocation.method(#addExplorerStatListener, [],
              {#explorerId: explorerId, #callback: callback}),
          returnValue: Future<dynamic>.value()) as _i17.Future<dynamic>);
  @override
  void removeFromExplorerLists({String? uid}) => super.noSuchMethod(
      Invocation.method(#removeFromExplorerLists, [], {#uid: uid}),
      returnValueForMissingStub: null);
  @override
  List<String> addToSupportedExplorersList({String? uid}) =>
      (super.noSuchMethod(
          Invocation.method(#addToSupportedExplorersList, [], {#uid: uid}),
          returnValue: <String>[]) as List<String>);
  @override
  bool isMatchingPasswords({String? hashedPw, String? stringPw}) =>
      (super.noSuchMethod(
          Invocation.method(#isMatchingPasswords, [],
              {#hashedPw: hashedPw, #stringPw: stringPw}),
          returnValue: false) as bool);
  @override
  String hashPassword(String? pw) => (super
          .noSuchMethod(Invocation.method(#hashPassword, [pw]), returnValue: '')
      as String);
  @override
  _i17.Future<dynamic> updateUserData({_i3.User? user}) =>
      (super.noSuchMethod(Invocation.method(#updateUserData, [], {#user: user}),
          returnValue: Future<dynamic>.value()) as _i17.Future<dynamic>);
  @override
  _i17.Future<dynamic> addSponsorIdToOtherUser(
          {String? otherUsersId, String? sponsorId}) =>
      (super.noSuchMethod(
          Invocation.method(#addSponsorIdToOtherUser, [],
              {#otherUsersId: otherUsersId, #sponsorId: sponsorId}),
          returnValue: Future<dynamic>.value()) as _i17.Future<dynamic>);
  @override
  _i17.Future<dynamic> isUserAlreadyPresent({dynamic name}) => (super
      .noSuchMethod(Invocation.method(#isUserAlreadyPresent, [], {#name: name}),
          returnValue: Future<dynamic>.value()) as _i17.Future<dynamic>);
  @override
  void cancelExplorerStatsListener({String? uid}) => super.noSuchMethod(
      Invocation.method(#cancelExplorerStatsListener, [], {#uid: uid}),
      returnValueForMissingStub: null);
  @override
  _i17.Future<dynamic> handleLogoutEvent() =>
      (super.noSuchMethod(Invocation.method(#handleLogoutEvent, []),
          returnValue: Future<dynamic>.value()) as _i17.Future<dynamic>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [FirestoreApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirestoreApi extends _i1.Mock implements _i20.FirestoreApi {
  @override
  _i2.Logger get log =>
      (super.noSuchMethod(Invocation.getter(#log), returnValue: _FakeLogger_0())
          as _i2.Logger);
  @override
  _i6.FirebaseFirestore get firestoreInstance =>
      (super.noSuchMethod(Invocation.getter(#firestoreInstance),
          returnValue: _FakeFirebaseFirestore_4()) as _i6.FirebaseFirestore);
  @override
  _i17.Future<void> createUser({_i3.User? user, _i4.UserStatistics? stats}) =>
      (super.noSuchMethod(
              Invocation.method(#createUser, [], {#user: user, #stats: stats}),
              returnValue: Future<void>.value(),
              returnValueForMissingStub: Future<void>.value())
          as _i17.Future<void>);
  @override
  _i17.Future<void> createUserInfo({_i3.User? user}) => (super.noSuchMethod(
      Invocation.method(#createUserInfo, [], {#user: user}),
      returnValue: Future<void>.value(),
      returnValueForMissingStub: Future<void>.value()) as _i17.Future<void>);
  @override
  _i17.Future<void> createUserStatistics(
          {String? uid, _i4.UserStatistics? stats}) =>
      (super.noSuchMethod(
              Invocation.method(
                  #createUserStatistics, [], {#uid: uid, #stats: stats}),
              returnValue: Future<void>.value(),
              returnValueForMissingStub: Future<void>.value())
          as _i17.Future<void>);
  @override
  _i17.Future<void> createUserFavouritePlaces(
          {dynamic userId, _i18.UserFavPlaces? favouritePlaces}) =>
      (super.noSuchMethod(
              Invocation.method(#createUserFavouritePlaces, [],
                  {#userId: userId, #favouritePlaces: favouritePlaces}),
              returnValue: Future<void>.value(),
              returnValueForMissingStub: Future<void>.value())
          as _i17.Future<void>);
  @override
  _i6.DocumentReference createUserDocument() =>
      (super.noSuchMethod(Invocation.method(#createUserDocument, []),
          returnValue: _FakeDocumentReference_5()) as _i6.DocumentReference);
  @override
  _i17.Future<_i3.User?> getUser({String? uid}) =>
      (super.noSuchMethod(Invocation.method(#getUser, [], {#uid: uid}),
          returnValue: Future<_i3.User?>.value()) as _i17.Future<_i3.User?>);
  @override
  _i17.Future<List<_i18.UserFavPlaces>?>? getUserFavouritePlaces(
          {String? userId}) =>
      (super.noSuchMethod(
              Invocation.method(#getUserFavouritePlaces, [], {#userId: userId}))
          as _i17.Future<List<_i18.UserFavPlaces>?>?);
  @override
  _i17.Future<_i3.User?> getUserWithName({String? name}) => (super.noSuchMethod(
      Invocation.method(#getUserWithName, [], {#name: name}),
      returnValue: Future<_i3.User?>.value()) as _i17.Future<_i3.User?>);
  @override
  _i17.Future<_i4.UserStatistics> getUserSummaryStatistics({String? uid}) =>
      (super.noSuchMethod(
              Invocation.method(#getUserSummaryStatistics, [], {#uid: uid}),
              returnValue:
                  Future<_i4.UserStatistics>.value(_FakeUserStatistics_2()))
          as _i17.Future<_i4.UserStatistics>);
  @override
  _i17.Stream<_i4.UserStatistics> getUserSummaryStatisticsStream(
          {String? uid}) =>
      (super.noSuchMethod(
          Invocation.method(#getUserSummaryStatisticsStream, [], {#uid: uid}),
          returnValue:
              Stream<_i4.UserStatistics>.empty()) as _i17
          .Stream<_i4.UserStatistics>);
  @override
  _i17.Future<dynamic> updateUserData({_i3.User? user}) =>
      (super.noSuchMethod(Invocation.method(#updateUserData, [], {#user: user}),
          returnValue: Future<dynamic>.value()) as _i17.Future<dynamic>);
  @override
  _i17.Future<dynamic> addSponsorIdToUser({String? uid, String? sponsorId}) =>
      (super.noSuchMethod(
          Invocation.method(
              #addSponsorIdToUser, [], {#uid: uid, #sponsorId: sponsorId}),
          returnValue: Future<dynamic>.value()) as _i17.Future<dynamic>);
  @override
  _i17.Stream<_i3.User> getUserStream({String? uid}) =>
      (super.noSuchMethod(Invocation.method(#getUserStream, [], {#uid: uid}),
          returnValue: Stream<_i3.User>.empty()) as _i17.Stream<_i3.User>);
  @override
  _i17.Stream<List<_i3.User>> getExplorersDataStream({String? uid}) =>
      (super.noSuchMethod(
              Invocation.method(#getExplorersDataStream, [], {#uid: uid}),
              returnValue: Stream<List<_i3.User>>.empty())
          as _i17.Stream<List<_i3.User>>);
  @override
  _i17.Future<List<_i21.PublicUserInfo>> queryExplorers(
          {String? queryString}) =>
      (super.noSuchMethod(
          Invocation.method(#queryExplorers, [], {#queryString: queryString}),
          returnValue: Future<List<_i21.PublicUserInfo>>.value(
              <_i21.PublicUserInfo>[])) as _i17
          .Future<List<_i21.PublicUserInfo>>);
  @override
  _i17.Stream<List<_i22.MoneyTransfer>> getTransferDataStream(
          {_i23.MoneyTransferQueryConfig? config, String? uid}) =>
      (super.noSuchMethod(
              Invocation.method(
                  #getTransferDataStream, [], {#config: config, #uid: uid}),
              returnValue: Stream<List<_i22.MoneyTransfer>>.empty())
          as _i17.Stream<List<_i22.MoneyTransfer>>);
  @override
  _i7.Quest getQuest({String? questId}) =>
      (super.noSuchMethod(Invocation.method(#getQuest, [], {#questId: questId}),
          returnValue: _FakeQuest_6()) as _i7.Quest);
  @override
  _i17.Future<dynamic> pushFinishedQuest({_i12.ActivatedQuest? quest}) => (super
      .noSuchMethod(Invocation.method(#pushFinishedQuest, [], {#quest: quest}),
          returnValue: Future<dynamic>.value()) as _i17.Future<dynamic>);
  @override
  _i17.Future<_i13.Marker?> getMarkerFromQrCodeId({String? qrCodeId}) =>
      (super.noSuchMethod(
          Invocation.method(#getMarkerFromQrCodeId, [], {#qrCodeId: qrCodeId}),
          returnValue:
              Future<_i13.Marker?>.value()) as _i17.Future<_i13.Marker?>);
  @override
  _i6.CollectionReference getUserStatisticsCollection({String? uid}) =>
      (super.noSuchMethod(
              Invocation.method(#getUserStatisticsCollection, [], {#uid: uid}),
              returnValue: _FakeCollectionReference_7())
          as _i6.CollectionReference);
  @override
  _i6.DocumentReference getUserSummaryStatisticsDocument({String? uid}) =>
      (super.noSuchMethod(
          Invocation.method(#getUserSummaryStatisticsDocument, [], {#uid: uid}),
          returnValue: _FakeDocumentReference_5()) as _i6.DocumentReference);
  @override
  _i6.DocumentReference getUserFavouritePlacesDocument({String? uid}) =>
      (super.noSuchMethod(
          Invocation.method(#getUserFavouritePlacesDocument, [], {#uid: uid}),
          returnValue: _FakeDocumentReference_5()) as _i6.DocumentReference);
  @override
  String toString() => super.toString();
}

/// A class which mocks [EnvironmentService].
///
/// See the documentation for Mockito's code generation for more information.
class MockEnvironmentService extends _i1.Mock
    implements _i24.EnvironmentService {
  @override
  _i2.Logger get log =>
      (super.noSuchMethod(Invocation.getter(#log), returnValue: _FakeLogger_0())
          as _i2.Logger);
  @override
  _i17.Future<dynamic> initialise() =>
      (super.noSuchMethod(Invocation.method(#initialise, []),
          returnValue: Future<dynamic>.value()) as _i17.Future<dynamic>);
  @override
  String getValue(String? key, {bool? verbose = false}) => (super.noSuchMethod(
      Invocation.method(#getValue, [key], {#verbose: verbose}),
      returnValue: '') as String);
  @override
  String toString() => super.toString();
}

/// A class which mocks [PlacesService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPlacesService extends _i1.Mock implements _i25.PlacesService {
  @override
  _i8.PlacesLocation get currentPosition =>
      (super.noSuchMethod(Invocation.getter(#currentPosition),
          returnValue: _FakePlacesLocation_8()) as _i8.PlacesLocation);
  @override
  void initialize({String? apiKey}) =>
      super.noSuchMethod(Invocation.method(#initialize, [], {#apiKey: apiKey}),
          returnValueForMissingStub: null);
  @override
  _i17.Future<List<_i8.PlacesAutoCompleteResult>> getAutoComplete(
          String? input) =>
      (super.noSuchMethod(Invocation.method(#getAutoComplete, [input]),
              returnValue: Future<List<_i8.PlacesAutoCompleteResult>>.value(
                  <_i8.PlacesAutoCompleteResult>[]))
          as _i17.Future<List<_i8.PlacesAutoCompleteResult>>);
  @override
  _i17.Future<_i8.PlacesDetails> getPlaceDetails(String? placeId) =>
      (super.noSuchMethod(Invocation.method(#getPlaceDetails, [placeId]),
              returnValue:
                  Future<_i8.PlacesDetails>.value(_FakePlacesDetails_9()))
          as _i17.Future<_i8.PlacesDetails>);
  @override
  _i17.Future<dynamic> getPlacesAtCurrentLocation() =>
      (super.noSuchMethod(Invocation.method(#getPlacesAtCurrentLocation, []),
          returnValue: Future<dynamic>.value()) as _i17.Future<dynamic>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [FlavorConfigProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockFlavorConfigProvider extends _i1.Mock
    implements _i26.FlavorConfigProvider {
  @override
  _i26.Flavor get flavor => (super.noSuchMethod(Invocation.getter(#flavor),
      returnValue: _i26.Flavor.unknown) as _i26.Flavor);
  @override
  set flavor(_i26.Flavor? _flavor) =>
      super.noSuchMethod(Invocation.setter(#flavor, _flavor),
          returnValueForMissingStub: null);
  @override
  String get appName =>
      (super.noSuchMethod(Invocation.getter(#appName), returnValue: '')
          as String);
  @override
  String get authority =>
      (super.noSuchMethod(Invocation.getter(#authority), returnValue: '')
          as String);
  @override
  String get uripathprepend =>
      (super.noSuchMethod(Invocation.getter(#uripathprepend), returnValue: '')
          as String);
  @override
  void configure(_i26.Flavor? flavorIn) =>
      super.noSuchMethod(Invocation.method(#configure, [flavorIn]),
          returnValueForMissingStub: null);
  @override
  String getTestUserEmail(_i16.UserRole? role) =>
      (super.noSuchMethod(Invocation.method(#getTestUserEmail, [role]),
          returnValue: '') as String);
  @override
  String getTestUserPassword() =>
      (super.noSuchMethod(Invocation.method(#getTestUserPassword, []),
          returnValue: '') as String);
  @override
  String getTestUserId(_i16.UserRole? role) =>
      (super.noSuchMethod(Invocation.method(#getTestUserId, [role]),
          returnValue: '') as String);
  @override
  String toString() => super.toString();
}

/// A class which mocks [LocalStorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalStorageService extends _i1.Mock
    implements _i27.LocalStorageService {
  @override
  _i2.Logger get log =>
      (super.noSuchMethod(Invocation.getter(#log), returnValue: _FakeLogger_0())
          as _i2.Logger);
  @override
  String get authTokenDataKey =>
      (super.noSuchMethod(Invocation.getter(#authTokenDataKey), returnValue: '')
          as String);
  @override
  set authTokenDataKey(String? _authTokenDataKey) => super.noSuchMethod(
      Invocation.setter(#authTokenDataKey, _authTokenDataKey),
      returnValueForMissingStub: null);
  @override
  _i17.Future<dynamic> saveToDisk({String? key, dynamic value}) =>
      (super.noSuchMethod(
          Invocation.method(#saveToDisk, [], {#key: key, #value: value}),
          returnValue: Future<dynamic>.value()) as _i17.Future<dynamic>);
  @override
  _i17.Future<dynamic> deleteFromDisk({String? key}) =>
      (super.noSuchMethod(Invocation.method(#deleteFromDisk, [], {#key: key}),
          returnValue: Future<dynamic>.value()) as _i17.Future<dynamic>);
  @override
  _i17.Future<dynamic> getFromDisk({String? key}) =>
      (super.noSuchMethod(Invocation.method(#getFromDisk, [], {#key: key}),
          returnValue: Future<dynamic>.value()) as _i17.Future<dynamic>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [FlutterSecureStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockFlutterSecureStorage extends _i1.Mock
    implements _i28.FlutterSecureStorage {
  @override
  _i17.Future<void> write(
          {String? key,
          String? value,
          _i28.IOSOptions? iOptions = _i28.IOSOptions.defaultOptions,
          _i28.AndroidOptions? aOptions,
          _i28.LinuxOptions? lOptions}) =>
      (super.noSuchMethod(
              Invocation.method(#write, [], {
                #key: key,
                #value: value,
                #iOptions: iOptions,
                #aOptions: aOptions,
                #lOptions: lOptions
              }),
              returnValue: Future<void>.value(),
              returnValueForMissingStub: Future<void>.value())
          as _i17.Future<void>);
  @override
  _i17.Future<String?> read(
          {String? key,
          _i28.IOSOptions? iOptions = _i28.IOSOptions.defaultOptions,
          _i28.AndroidOptions? aOptions,
          _i28.LinuxOptions? lOptions}) =>
      (super.noSuchMethod(
          Invocation.method(#read, [], {
            #key: key,
            #iOptions: iOptions,
            #aOptions: aOptions,
            #lOptions: lOptions
          }),
          returnValue: Future<String?>.value()) as _i17.Future<String?>);
  @override
  _i17.Future<bool> containsKey(
          {String? key,
          _i28.IOSOptions? iOptions = _i28.IOSOptions.defaultOptions,
          _i28.AndroidOptions? aOptions,
          _i28.LinuxOptions? lOptions}) =>
      (super.noSuchMethod(
          Invocation.method(#containsKey, [], {
            #key: key,
            #iOptions: iOptions,
            #aOptions: aOptions,
            #lOptions: lOptions
          }),
          returnValue: Future<bool>.value(false)) as _i17.Future<bool>);
  @override
  _i17.Future<void> delete(
          {String? key,
          _i28.IOSOptions? iOptions = _i28.IOSOptions.defaultOptions,
          _i28.AndroidOptions? aOptions,
          _i28.LinuxOptions? lOptions}) =>
      (super.noSuchMethod(
              Invocation.method(#delete, [], {
                #key: key,
                #iOptions: iOptions,
                #aOptions: aOptions,
                #lOptions: lOptions
              }),
              returnValue: Future<void>.value(),
              returnValueForMissingStub: Future<void>.value())
          as _i17.Future<void>);
  @override
  _i17.Future<Map<String, String>> readAll(
          {_i28.IOSOptions? iOptions = _i28.IOSOptions.defaultOptions,
          _i28.AndroidOptions? aOptions,
          _i28.LinuxOptions? lOptions}) =>
      (super.noSuchMethod(
              Invocation.method(#readAll, [], {
                #iOptions: iOptions,
                #aOptions: aOptions,
                #lOptions: lOptions
              }),
              returnValue:
                  Future<Map<String, String>>.value(<String, String>{}))
          as _i17.Future<Map<String, String>>);
  @override
  _i17.Future<void> deleteAll(
          {_i28.IOSOptions? iOptions = _i28.IOSOptions.defaultOptions,
          _i28.AndroidOptions? aOptions,
          _i28.LinuxOptions? lOptions}) =>
      (super.noSuchMethod(
              Invocation.method(#deleteAll, [], {
                #iOptions: iOptions,
                #aOptions: aOptions,
                #lOptions: lOptions
              }),
              returnValue: Future<void>.value(),
              returnValueForMissingStub: Future<void>.value())
          as _i17.Future<void>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [LayoutService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLayoutService extends _i1.Mock implements _i29.LayoutService {
  @override
  _i9.BehaviorSubject<bool> get showBottomNavBarSubject =>
      (super.noSuchMethod(Invocation.getter(#showBottomNavBarSubject),
              returnValue: _FakeBehaviorSubject_10<bool>())
          as _i9.BehaviorSubject<bool>);
  @override
  set showBottomNavBarSubject(
          _i9.BehaviorSubject<bool>? _showBottomNavBarSubject) =>
      super.noSuchMethod(
          Invocation.setter(#showBottomNavBarSubject, _showBottomNavBarSubject),
          returnValueForMissingStub: null);
  @override
  bool get showBottomNavBar =>
      (super.noSuchMethod(Invocation.getter(#showBottomNavBar),
          returnValue: false) as bool);
  @override
  void setShowBottomNavBar(bool? show) =>
      super.noSuchMethod(Invocation.method(#setShowBottomNavBar, [show]),
          returnValueForMissingStub: null);
  @override
  String toString() => super.toString();
}

/// A class which mocks [TransfersHistoryService].
///
/// See the documentation for Mockito's code generation for more information.
class MockTransfersHistoryService extends _i1.Mock
    implements _i30.TransfersHistoryService {
  @override
  _i2.Logger get log =>
      (super.noSuchMethod(Invocation.getter(#log), returnValue: _FakeLogger_0())
          as _i2.Logger);
  @override
  Map<_i23.MoneyTransferQueryConfig, List<_i22.MoneyTransfer>>
      get latestTransfers => (super
              .noSuchMethod(Invocation.getter(#latestTransfers), returnValue: <
                  _i23.MoneyTransferQueryConfig, List<_i22.MoneyTransfer>>{})
          as Map<_i23.MoneyTransferQueryConfig, List<_i22.MoneyTransfer>>);
  @override
  set latestTransfers(
          Map<_i23.MoneyTransferQueryConfig, List<_i22.MoneyTransfer>>?
              _latestTransfers) =>
      super.noSuchMethod(Invocation.setter(#latestTransfers, _latestTransfers),
          returnValueForMissingStub: null);
  @override
  _i3.User get currentUser =>
      (super.noSuchMethod(Invocation.getter(#currentUser),
          returnValue: _FakeUser_1()) as _i3.User);
  @override
  _i17.Stream<List<_i22.MoneyTransfer>> getTransferDataStream(
          {_i23.MoneyTransferQueryConfig? config}) =>
      (super.noSuchMethod(
              Invocation.method(#getTransferDataStream, [], {#config: config}),
              returnValue: Stream<List<_i22.MoneyTransfer>>.empty())
          as _i17.Stream<List<_i22.MoneyTransfer>>);
  @override
  List<_i22.MoneyTransfer> getTransfers(
          {_i23.MoneyTransferQueryConfig? config}) =>
      (super.noSuchMethod(
          Invocation.method(#getTransfers, [], {#config: config}),
          returnValue: <_i22.MoneyTransfer>[]) as List<_i22.MoneyTransfer>);
  @override
  void addTransferDataListener(
          {_i23.MoneyTransferQueryConfig? config,
          _i17.Completer<void>? completer,
          void Function()? callback}) =>
      super.noSuchMethod(
          Invocation.method(#addTransferDataListener, [],
              {#config: config, #completer: completer, #callback: callback}),
          returnValueForMissingStub: null);
  @override
  void pauseTransferDataListener({_i23.MoneyTransferQueryConfig? config}) =>
      super.noSuchMethod(
          Invocation.method(#pauseTransferDataListener, [], {#config: config}),
          returnValueForMissingStub: null);
  @override
  void cancelTransferDataListener({_i23.MoneyTransferQueryConfig? config}) =>
      super.noSuchMethod(
          Invocation.method(#cancelTransferDataListener, [], {#config: config}),
          returnValueForMissingStub: null);
  @override
  List<_i22.MoneyTransfer> getMoneyTransfersWithUniqueSender(
          List<_i22.MoneyTransfer>? transfer) =>
      (super.noSuchMethod(
          Invocation.method(#getMoneyTransfersWithUniqueSender, [transfer]),
          returnValue: <_i22.MoneyTransfer>[]) as List<_i22.MoneyTransfer>);
  @override
  void clearData() => super.noSuchMethod(Invocation.method(#clearData, []),
      returnValueForMissingStub: null);
  @override
  String toString() => super.toString();
}

/// A class which mocks [GeolocationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockGeolocationService extends _i1.Mock
    implements _i31.GeolocationService {
  @override
  _i2.Logger get log =>
      (super.noSuchMethod(Invocation.getter(#log), returnValue: _FakeLogger_0())
          as _i2.Logger);
  @override
  _i10.Position get getUserPosition =>
      (super.noSuchMethod(Invocation.getter(#getUserPosition),
          returnValue: _FakePosition_11()) as _i10.Position);
  @override
  _i11.CameraPosition getInitialCameraPostion() =>
      (super.noSuchMethod(Invocation.method(#getInitialCameraPostion, []),
          returnValue: _FakeCameraPosition_12()) as _i11.CameraPosition);
  @override
  _i17.Future<dynamic> getCurrentLocation() =>
      (super.noSuchMethod(Invocation.method(#getCurrentLocation, []),
          returnValue: Future<dynamic>.value()) as _i17.Future<dynamic>);
  @override
  _i17.Future<dynamic> setUserPosition({_i10.Position? position}) =>
      (super.noSuchMethod(
          Invocation.method(#setUserPosition, [], {#position: position}),
          returnValue: Future<dynamic>.value()) as _i17.Future<dynamic>);
  @override
  _i17.Future<bool> checkGeolocationAvailable() =>
      (super.noSuchMethod(Invocation.method(#checkGeolocationAvailable, []),
          returnValue: Future<bool>.value(false)) as _i17.Future<bool>);
  @override
  _i17.Future<bool> handlePermission() =>
      (super.noSuchMethod(Invocation.method(#handlePermission, []),
          returnValue: Future<bool>.value(false)) as _i17.Future<bool>);
  @override
  _i17.Future<bool> isUserCloseby({double? lat, double? lon}) =>
      (super.noSuchMethod(
          Invocation.method(#isUserCloseby, [], {#lat: lat, #lon: lon}),
          returnValue: Future<bool>.value(false)) as _i17.Future<bool>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [QuestService].
///
/// See the documentation for Mockito's code generation for more information.
class MockQuestService extends _i1.Mock implements _i32.QuestService {
  @override
  _i9.BehaviorSubject<_i12.ActivatedQuest?> get activatedQuestSubject =>
      (super.noSuchMethod(Invocation.getter(#activatedQuestSubject),
              returnValue: _FakeBehaviorSubject_10<_i12.ActivatedQuest?>())
          as _i9.BehaviorSubject<_i12.ActivatedQuest?>);
  @override
  set activatedQuestSubject(
          _i9.BehaviorSubject<_i12.ActivatedQuest?>? _activatedQuestSubject) =>
      super.noSuchMethod(
          Invocation.setter(#activatedQuestSubject, _activatedQuestSubject),
          returnValueForMissingStub: null);
  @override
  _i2.Logger get log =>
      (super.noSuchMethod(Invocation.getter(#log), returnValue: _FakeLogger_0())
          as _i2.Logger);
  @override
  _i17.Future<dynamic> startQuest({_i7.Quest? quest}) =>
      (super.noSuchMethod(Invocation.method(#startQuest, [], {#quest: quest}),
          returnValue: Future<dynamic>.value()) as _i17.Future<dynamic>);
  @override
  _i17.Future<dynamic> evaluateAndFinishQuest() =>
      (super.noSuchMethod(Invocation.method(#evaluateAndFinishQuest, []),
          returnValue: Future<dynamic>.value()) as _i17.Future<dynamic>);
  @override
  _i17.Future<dynamic> continueIncompleteQuest() =>
      (super.noSuchMethod(Invocation.method(#continueIncompleteQuest, []),
          returnValue: Future<dynamic>.value()) as _i17.Future<dynamic>);
  @override
  _i17.Future<dynamic> cancelIncompleteQuest() =>
      (super.noSuchMethod(Invocation.method(#cancelIncompleteQuest, []),
          returnValue: Future<dynamic>.value()) as _i17.Future<dynamic>);
  @override
  void evaluateQuest() =>
      super.noSuchMethod(Invocation.method(#evaluateQuest, []),
          returnValueForMissingStub: null);
  @override
  _i17.Future<dynamic> trackData(int? seconds) =>
      (super.noSuchMethod(Invocation.method(#trackData, [seconds]),
          returnValue: Future<dynamic>.value()) as _i17.Future<dynamic>);
  @override
  _i17.Future<dynamic> verifyAndUpdateCollectedMarkers({_i13.Marker? marker}) =>
      (super.noSuchMethod(
          Invocation.method(
              #verifyAndUpdateCollectedMarkers, [], {#marker: marker}),
          returnValue: Future<dynamic>.value()) as _i17.Future<dynamic>);
  @override
  void updateCollectedMarkers({_i13.Marker? marker}) => super.noSuchMethod(
      Invocation.method(#updateCollectedMarkers, [], {#marker: marker}),
      returnValueForMissingStub: null);
  @override
  void pushActivatedQuest(_i12.ActivatedQuest? quest) =>
      super.noSuchMethod(Invocation.method(#pushActivatedQuest, [quest]),
          returnValueForMissingStub: null);
  @override
  void removeActivatedQuest() =>
      super.noSuchMethod(Invocation.method(#removeActivatedQuest, []),
          returnValueForMissingStub: null);
  @override
  bool isMarkerInQuest({_i13.Marker? marker}) => (super.noSuchMethod(
      Invocation.method(#isMarkerInQuest, [], {#marker: marker}),
      returnValue: false) as bool);
  @override
  _i17.Future<dynamic> getQuest({String? questId}) =>
      (super.noSuchMethod(Invocation.method(#getQuest, [], {#questId: questId}),
          returnValue: Future<dynamic>.value()) as _i17.Future<dynamic>);
  @override
  void updateTime(int? seconds) =>
      super.noSuchMethod(Invocation.method(#updateTime, [seconds]),
          returnValueForMissingStub: null);
  @override
  _i12.ActivatedQuest updateTimeOnQuest(
          _i12.ActivatedQuest? activatedQuest, int? seconds) =>
      (super.noSuchMethod(
          Invocation.method(#updateTimeOnQuest, [activatedQuest, seconds]),
          returnValue: _FakeActivatedQuest_13()) as _i12.ActivatedQuest);
  @override
  void disposeActivatedQuest() =>
      super.noSuchMethod(Invocation.method(#disposeActivatedQuest, []),
          returnValueForMissingStub: null);
  @override
  _i12.ActivatedQuest getActivatedQuest({_i7.Quest? quest}) => (super
      .noSuchMethod(Invocation.method(#getActivatedQuest, [], {#quest: quest}),
          returnValue: _FakeActivatedQuest_13()) as _i12.ActivatedQuest);
  @override
  String toString() => super.toString();
}

/// A class which mocks [StopWatchService].
///
/// See the documentation for Mockito's code generation for more information.
class MockStopWatchService extends _i1.Mock implements _i33.StopWatchService {
  @override
  _i2.Logger get log =>
      (super.noSuchMethod(Invocation.getter(#log), returnValue: _FakeLogger_0())
          as _i2.Logger);
  @override
  void startTimer() => super.noSuchMethod(Invocation.method(#startTimer, []),
      returnValueForMissingStub: null);
  @override
  void stopTimer() => super.noSuchMethod(Invocation.method(#stopTimer, []),
      returnValueForMissingStub: null);
  @override
  void resetTimer() => super.noSuchMethod(Invocation.method(#resetTimer, []),
      returnValueForMissingStub: null);
  @override
  int getSecondTime() =>
      (super.noSuchMethod(Invocation.method(#getSecondTime, []), returnValue: 0)
          as int);
  @override
  void listenToSecondTime({_i17.Future<dynamic> Function(int)? callback}) =>
      super.noSuchMethod(
          Invocation.method(#listenToSecondTime, [], {#callback: callback}),
          returnValueForMissingStub: null);
  @override
  void cancelListener() =>
      super.noSuchMethod(Invocation.method(#cancelListener, []),
          returnValueForMissingStub: null);
  @override
  void pauseListener() =>
      super.noSuchMethod(Invocation.method(#pauseListener, []),
          returnValueForMissingStub: null);
  @override
  void resumeListener() =>
      super.noSuchMethod(Invocation.method(#resumeListener, []),
          returnValueForMissingStub: null);
  @override
  String toString() => super.toString();
}

/// A class which mocks [MarkerService].
///
/// See the documentation for Mockito's code generation for more information.
class MockMarkerService extends _i1.Mock implements _i34.MarkerService {
  @override
  _i2.Logger get log =>
      (super.noSuchMethod(Invocation.getter(#log), returnValue: _FakeLogger_0())
          as _i2.Logger);
  @override
  _i17.Future<bool> isUserCloseby({_i13.Marker? marker}) => (super.noSuchMethod(
      Invocation.method(#isUserCloseby, [], {#marker: marker}),
      returnValue: Future<bool>.value(false)) as _i17.Future<bool>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [QRCodeService].
///
/// See the documentation for Mockito's code generation for more information.
class MockQRCodeService extends _i1.Mock implements _i35.QRCodeService {
  @override
  _i13.Marker convertQrCodeStringToMarker({String? qrCodeString}) =>
      (super.noSuchMethod(
          Invocation.method(
              #convertQrCodeStringToMarker, [], {#qrCodeString: qrCodeString}),
          returnValue: _FakeMarker_14()) as _i13.Marker);
  @override
  String convertMarkerToQrCodeString({_i13.Marker? marker}) =>
      (super.noSuchMethod(
          Invocation.method(
              #convertMarkerToQrCodeString, [], {#marker: marker}),
          returnValue: '') as String);
  @override
  _i17.Future<dynamic> getMarkerFromQrCodeString({String? qrCodeString}) =>
      (super.noSuchMethod(
          Invocation.method(
              #getMarkerFromQrCodeString, [], {#qrCodeString: qrCodeString}),
          returnValue: Future<dynamic>.value()) as _i17.Future<dynamic>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [NavigationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNavigationService extends _i1.Mock implements _i36.NavigationService {
  @override
  String get previousRoute =>
      (super.noSuchMethod(Invocation.getter(#previousRoute), returnValue: '')
          as String);
  @override
  String get currentRoute =>
      (super.noSuchMethod(Invocation.getter(#currentRoute), returnValue: '')
          as String);
  @override
  _i37.GlobalKey<_i37.NavigatorState>? nestedNavigationKey(int? index) =>
      (super.noSuchMethod(Invocation.method(#nestedNavigationKey, [index]))
          as _i37.GlobalKey<_i37.NavigatorState>?);
  @override
  void config(
          {bool? enableLog,
          bool? defaultPopGesture,
          bool? defaultOpaqueRoute,
          Duration? defaultDurationTransition,
          bool? defaultGlobalState,
          String? defaultTransition}) =>
      super.noSuchMethod(
          Invocation.method(#config, [], {
            #enableLog: enableLog,
            #defaultPopGesture: defaultPopGesture,
            #defaultOpaqueRoute: defaultOpaqueRoute,
            #defaultDurationTransition: defaultDurationTransition,
            #defaultGlobalState: defaultGlobalState,
            #defaultTransition: defaultTransition
          }),
          returnValueForMissingStub: null);
  @override
  _i17.Future<T?>? navigateWithTransition<T>(_i37.Widget? page,
          {bool? opaque,
          String? transition = r'',
          Duration? duration,
          bool? popGesture,
          int? id,
          _i37.Curve? curve,
          _i36.Bindings? binding,
          bool? fullscreenDialog = false,
          bool? preventDuplicates = true,
          _i36.Transition? transitionClass}) =>
      (super.noSuchMethod(Invocation.method(#navigateWithTransition, [
        page
      ], {
        #opaque: opaque,
        #transition: transition,
        #duration: duration,
        #popGesture: popGesture,
        #id: id,
        #curve: curve,
        #binding: binding,
        #fullscreenDialog: fullscreenDialog,
        #preventDuplicates: preventDuplicates,
        #transitionClass: transitionClass
      })) as _i17.Future<T?>?);
  @override
  _i17.Future<T?>? replaceWithTransition<T>(_i37.Widget? page,
          {bool? opaque,
          String? transition = r'',
          Duration? duration,
          bool? popGesture,
          int? id,
          _i37.Curve? curve,
          _i36.Bindings? binding,
          bool? fullscreenDialog = false,
          bool? preventDuplicates = true,
          _i36.Transition? transitionClass}) =>
      (super.noSuchMethod(Invocation.method(#replaceWithTransition, [
        page
      ], {
        #opaque: opaque,
        #transition: transition,
        #duration: duration,
        #popGesture: popGesture,
        #id: id,
        #curve: curve,
        #binding: binding,
        #fullscreenDialog: fullscreenDialog,
        #preventDuplicates: preventDuplicates,
        #transitionClass: transitionClass
      })) as _i17.Future<T?>?);
  @override
  bool back<T>({T? result, int? id}) => (super.noSuchMethod(
      Invocation.method(#back, [], {#result: result, #id: id}),
      returnValue: false) as bool);
  @override
  void popUntil(_i37.RoutePredicate? predicate) =>
      super.noSuchMethod(Invocation.method(#popUntil, [predicate]),
          returnValueForMissingStub: null);
  @override
  void popRepeated(int? popTimes) =>
      super.noSuchMethod(Invocation.method(#popRepeated, [popTimes]),
          returnValueForMissingStub: null);
  @override
  _i17.Future<T?>? navigateTo<T>(String? routeName,
          {dynamic arguments,
          int? id,
          bool? preventDuplicates = true,
          Map<String, String>? parameters}) =>
      (super.noSuchMethod(Invocation.method(#navigateTo, [
        routeName
      ], {
        #arguments: arguments,
        #id: id,
        #preventDuplicates: preventDuplicates,
        #parameters: parameters
      })) as _i17.Future<T?>?);
  @override
  _i17.Future<T?>? navigateToView<T>(_i37.Widget? view,
          {dynamic arguments,
          int? id,
          bool? opaque,
          _i37.Curve? curve,
          _i36.Bindings? binding,
          Duration? duration,
          bool? fullscreenDialog = false,
          bool? popGesture,
          bool? preventDuplicates = true,
          _i36.Transition? transition}) =>
      (super.noSuchMethod(Invocation.method(#navigateToView, [
        view
      ], {
        #arguments: arguments,
        #id: id,
        #opaque: opaque,
        #curve: curve,
        #binding: binding,
        #duration: duration,
        #fullscreenDialog: fullscreenDialog,
        #popGesture: popGesture,
        #preventDuplicates: preventDuplicates,
        #transition: transition
      })) as _i17.Future<T?>?);
  @override
  _i17.Future<T?>? replaceWith<T>(String? routeName,
          {dynamic arguments,
          int? id,
          bool? preventDuplicates = true,
          Map<String, String>? parameters}) =>
      (super.noSuchMethod(Invocation.method(#replaceWith, [
        routeName
      ], {
        #arguments: arguments,
        #id: id,
        #preventDuplicates: preventDuplicates,
        #parameters: parameters
      })) as _i17.Future<T?>?);
  @override
  _i17.Future<T?>? clearStackAndShow<T>(String? routeName,
          {dynamic arguments, int? id, Map<String, String>? parameters}) =>
      (super.noSuchMethod(Invocation.method(#clearStackAndShow, [
        routeName
      ], {
        #arguments: arguments,
        #id: id,
        #parameters: parameters
      })) as _i17.Future<T?>?);
  @override
  _i17.Future<T?>? clearTillFirstAndShow<T>(String? routeName,
          {dynamic arguments,
          int? id,
          bool? preventDuplicates = true,
          Map<String, String>? parameters}) =>
      (super.noSuchMethod(Invocation.method(#clearTillFirstAndShow, [
        routeName
      ], {
        #arguments: arguments,
        #id: id,
        #preventDuplicates: preventDuplicates,
        #parameters: parameters
      })) as _i17.Future<T?>?);
  @override
  _i17.Future<T?>? clearTillFirstAndShowView<T>(_i37.Widget? view,
          {dynamic arguments, int? id}) =>
      (super.noSuchMethod(Invocation.method(#clearTillFirstAndShowView, [view],
          {#arguments: arguments, #id: id})) as _i17.Future<T?>?);
  @override
  _i17.Future<T?>? pushNamedAndRemoveUntil<T>(String? routeName,
          {_i37.RoutePredicate? predicate, dynamic arguments, int? id}) =>
      (super.noSuchMethod(Invocation.method(#pushNamedAndRemoveUntil, [
        routeName
      ], {
        #predicate: predicate,
        #arguments: arguments,
        #id: id
      })) as _i17.Future<T?>?);
  @override
  String toString() => super.toString();
}

/// A class which mocks [SnackbarService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSnackbarService extends _i1.Mock implements _i36.SnackbarService {
  @override
  void registerSnackbarConfig(_i36.SnackbarConfig? config) =>
      super.noSuchMethod(Invocation.method(#registerSnackbarConfig, [config]),
          returnValueForMissingStub: null);
  @override
  void registerCustomSnackbarconfig(
          {dynamic customData, _i36.SnackbarConfig? config}) =>
      super.noSuchMethod(
          Invocation.method(#registerCustomSnackbarconfig, [],
              {#customData: customData, #config: config}),
          returnValueForMissingStub: null);
  @override
  void registerCustomMainButtonBuilder(
          {dynamic variant,
          _i37.Widget Function(String?, Function?)? builder}) =>
      super.noSuchMethod(
          Invocation.method(#registerCustomMainButtonBuilder, [],
              {#variant: variant, #builder: builder}),
          returnValueForMissingStub: null);
  @override
  void registerCustomSnackbarConfig(
          {dynamic variant,
          _i36.SnackbarConfig? config,
          _i36.SnackbarConfig Function()? configBuilder}) =>
      super.noSuchMethod(
          Invocation.method(#registerCustomSnackbarConfig, [], {
            #variant: variant,
            #config: config,
            #configBuilder: configBuilder
          }),
          returnValueForMissingStub: null);
  @override
  void showSnackbar(
          {String? title = r'',
          String? message,
          dynamic Function(dynamic)? onTap,
          Duration? duration = const Duration(seconds: 3),
          String? mainButtonTitle,
          void Function()? onMainButtonTapped}) =>
      super.noSuchMethod(
          Invocation.method(#showSnackbar, [], {
            #title: title,
            #message: message,
            #onTap: onTap,
            #duration: duration,
            #mainButtonTitle: mainButtonTitle,
            #onMainButtonTapped: onMainButtonTapped
          }),
          returnValueForMissingStub: null);
  @override
  _i17.Future<dynamic>? showCustomSnackBar(
          {String? message,
          dynamic customData,
          dynamic variant,
          String? title,
          String? mainButtonTitle,
          void Function()? onMainButtonTapped,
          Function? onTap,
          Duration? duration = const Duration(seconds: 1)}) =>
      (super.noSuchMethod(Invocation.method(#showCustomSnackBar, [], {
        #message: message,
        #customData: customData,
        #variant: variant,
        #title: title,
        #mainButtonTitle: mainButtonTitle,
        #onMainButtonTapped: onMainButtonTapped,
        #onTap: onTap,
        #duration: duration
      })) as _i17.Future<dynamic>?);
  @override
  String toString() => super.toString();
}

/// A class which mocks [DialogService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDialogService extends _i1.Mock implements _i36.DialogService {
  @override
  void registerCustomDialogBuilders(
          Map<dynamic, _i36.DialogBuilder>? builders) =>
      super.noSuchMethod(
          Invocation.method(#registerCustomDialogBuilders, [builders]),
          returnValueForMissingStub: null);
  @override
  void registerCustomDialogBuilder(
          {dynamic variant,
          _i37.Widget Function(_i37.BuildContext, _i36.DialogRequest<dynamic>,
                  dynamic Function(_i36.DialogResponse<dynamic>))?
              builder}) =>
      super.noSuchMethod(
          Invocation.method(#registerCustomDialogBuilder, [],
              {#variant: variant, #builder: builder}),
          returnValueForMissingStub: null);
  @override
  _i17.Future<_i36.DialogResponse<dynamic>?> showDialog(
          {String? title,
          String? description,
          String? cancelTitle,
          _i38.Color? cancelTitleColor,
          String? buttonTitle = r'Ok',
          _i38.Color? buttonTitleColor,
          bool? barrierDismissible = false,
          _i36.DialogPlatform? dialogPlatform}) =>
      (super.noSuchMethod(
              Invocation.method(#showDialog, [], {
                #title: title,
                #description: description,
                #cancelTitle: cancelTitle,
                #cancelTitleColor: cancelTitleColor,
                #buttonTitle: buttonTitle,
                #buttonTitleColor: buttonTitleColor,
                #barrierDismissible: barrierDismissible,
                #dialogPlatform: dialogPlatform
              }),
              returnValue: Future<_i36.DialogResponse<dynamic>?>.value())
          as _i17.Future<_i36.DialogResponse<dynamic>?>);
  @override
  _i17.Future<_i36.DialogResponse<T>?> showCustomDialog<T, R>(
          {dynamic variant,
          String? title,
          String? description,
          bool? hasImage = false,
          String? imageUrl,
          bool? showIconInMainButton = false,
          String? mainButtonTitle,
          bool? showIconInSecondaryButton = false,
          String? secondaryButtonTitle,
          bool? showIconInAdditionalButton = false,
          String? additionalButtonTitle,
          bool? takesInput = false,
          _i38.Color? barrierColor = const _i38.Color(2315255808),
          bool? barrierDismissible = false,
          String? barrierLabel = r'',
          dynamic customData,
          R? data}) =>
      (super.noSuchMethod(
              Invocation.method(#showCustomDialog, [], {
                #variant: variant,
                #title: title,
                #description: description,
                #hasImage: hasImage,
                #imageUrl: imageUrl,
                #showIconInMainButton: showIconInMainButton,
                #mainButtonTitle: mainButtonTitle,
                #showIconInSecondaryButton: showIconInSecondaryButton,
                #secondaryButtonTitle: secondaryButtonTitle,
                #showIconInAdditionalButton: showIconInAdditionalButton,
                #additionalButtonTitle: additionalButtonTitle,
                #takesInput: takesInput,
                #barrierColor: barrierColor,
                #barrierDismissible: barrierDismissible,
                #barrierLabel: barrierLabel,
                #customData: customData,
                #data: data
              }),
              returnValue: Future<_i36.DialogResponse<T>?>.value())
          as _i17.Future<_i36.DialogResponse<T>?>);
  @override
  _i17.Future<_i36.DialogResponse<dynamic>?> showConfirmationDialog(
          {String? title,
          String? description,
          String? cancelTitle = r'Cancel',
          String? confirmationTitle = r'Ok',
          bool? barrierDismissible = false,
          _i36.DialogPlatform? dialogPlatform}) =>
      (super.noSuchMethod(
              Invocation.method(#showConfirmationDialog, [], {
                #title: title,
                #description: description,
                #cancelTitle: cancelTitle,
                #confirmationTitle: confirmationTitle,
                #barrierDismissible: barrierDismissible,
                #dialogPlatform: dialogPlatform
              }),
              returnValue: Future<_i36.DialogResponse<dynamic>?>.value())
          as _i17.Future<_i36.DialogResponse<dynamic>?>);
  @override
  void completeDialog(_i36.DialogResponse<dynamic>? response) =>
      super.noSuchMethod(Invocation.method(#completeDialog, [response]),
          returnValueForMissingStub: null);
  @override
  String toString() => super.toString();
}

/// A class which mocks [FirebaseAuthenticationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirebaseAuthenticationService extends _i1.Mock
    implements _i15.FirebaseAuthenticationService {
  @override
  _i14.FirebaseAuth get firebaseAuth =>
      (super.noSuchMethod(Invocation.getter(#firebaseAuth),
          returnValue: _FakeFirebaseAuth_15()) as _i14.FirebaseAuth);
  @override
  bool get hasUser =>
      (super.noSuchMethod(Invocation.getter(#hasUser), returnValue: false)
          as bool);
  @override
  _i17.Stream<_i14.User?> get authStateChanges =>
      (super.noSuchMethod(Invocation.getter(#authStateChanges),
          returnValue: Stream<_i14.User?>.empty()) as _i17.Stream<_i14.User?>);
  @override
  _i17.Future<bool> emailExists(String? email) =>
      (super.noSuchMethod(Invocation.method(#emailExists, [email]),
          returnValue: Future<bool>.value(false)) as _i17.Future<bool>);
  @override
  _i17.Future<_i15.FirebaseAuthenticationResult> signInWithGoogle() =>
      (super.noSuchMethod(Invocation.method(#signInWithGoogle, []),
              returnValue: Future<_i15.FirebaseAuthenticationResult>.value(
                  _FakeFirebaseAuthenticationResult_16()))
          as _i17.Future<_i15.FirebaseAuthenticationResult>);
  @override
  _i17.Future<bool> isAppleSignInAvailable() =>
      (super.noSuchMethod(Invocation.method(#isAppleSignInAvailable, []),
          returnValue: Future<bool>.value(false)) as _i17.Future<bool>);
  @override
  _i17.Future<_i15.FirebaseAuthenticationResult> signInWithApple(
          {String? appleRedirectUri, String? appleClientId}) =>
      (super.noSuchMethod(
              Invocation.method(#signInWithApple, [], {
                #appleRedirectUri: appleRedirectUri,
                #appleClientId: appleClientId
              }),
              returnValue: Future<_i15.FirebaseAuthenticationResult>.value(
                  _FakeFirebaseAuthenticationResult_16()))
          as _i17.Future<_i15.FirebaseAuthenticationResult>);
  @override
  _i17.Future<_i15.FirebaseAuthenticationResult> loginAnonymously() =>
      (super.noSuchMethod(Invocation.method(#loginAnonymously, []),
              returnValue: Future<_i15.FirebaseAuthenticationResult>.value(
                  _FakeFirebaseAuthenticationResult_16()))
          as _i17.Future<_i15.FirebaseAuthenticationResult>);
  @override
  _i17.Future<_i15.FirebaseAuthenticationResult> loginWithEmail(
          {String? email, String? password}) =>
      (super.noSuchMethod(
              Invocation.method(
                  #loginWithEmail, [], {#email: email, #password: password}),
              returnValue: Future<_i15.FirebaseAuthenticationResult>.value(
                  _FakeFirebaseAuthenticationResult_16()))
          as _i17.Future<_i15.FirebaseAuthenticationResult>);
  @override
  _i17.Future<_i15.FirebaseAuthenticationResult> createAccountWithEmail(
          {String? email, String? password}) =>
      (super.noSuchMethod(
              Invocation.method(#createAccountWithEmail, [],
                  {#email: email, #password: password}),
              returnValue: Future<_i15.FirebaseAuthenticationResult>.value(
                  _FakeFirebaseAuthenticationResult_16()))
          as _i17.Future<_i15.FirebaseAuthenticationResult>);
  @override
  _i17.Future<dynamic> logout() =>
      (super.noSuchMethod(Invocation.method(#logout, []),
          returnValue: Future<dynamic>.value()) as _i17.Future<dynamic>);
  @override
  _i17.Future<dynamic> sendResetPasswordLink(String? email) =>
      (super.noSuchMethod(Invocation.method(#sendResetPasswordLink, [email]),
          returnValue: Future<dynamic>.value()) as _i17.Future<dynamic>);
  @override
  _i17.Future<dynamic> validatePassword(String? password) =>
      (super.noSuchMethod(Invocation.method(#validatePassword, [password]),
          returnValue: Future<dynamic>.value()) as _i17.Future<dynamic>);
  @override
  _i17.Future<dynamic> updatePassword(String? password) =>
      (super.noSuchMethod(Invocation.method(#updatePassword, [password]),
          returnValue: Future<dynamic>.value()) as _i17.Future<dynamic>);
  @override
  _i17.Future<dynamic> updateEmail(String? email) =>
      (super.noSuchMethod(Invocation.method(#updateEmail, [email]),
          returnValue: Future<dynamic>.value()) as _i17.Future<dynamic>);
  @override
  String generateNonce([int? length = 32]) =>
      (super.noSuchMethod(Invocation.method(#generateNonce, [length]),
          returnValue: '') as String);
  @override
  String sha256ofString(String? input) =>
      (super.noSuchMethod(Invocation.method(#sha256ofString, [input]),
          returnValue: '') as String);
  @override
  String toString() => super.toString();
}
