// Mocks generated by Mockito 5.0.14 from annotations
// in afkcredits/test/helpers/test_helpers.dart.
// Do not manually edit this file.

import 'dart:async' as _i11;
import 'dart:ui' as _i22;

import 'package:afkcredits/apis/firestore_api.dart' as _i13;
import 'package:afkcredits/datamodels/users/public_user_info.dart' as _i14;
import 'package:afkcredits/datamodels/users/user.dart' as _i3;
import 'package:afkcredits/datamodels/users/user_statistics.dart' as _i4;
import 'package:afkcredits/enums/authentication_method.dart' as _i12;
import 'package:afkcredits/enums/user_role.dart' as _i10;
import 'package:afkcredits/flavor_config.dart' as _i17;
import 'package:afkcredits/services/environment_services.dart' as _i15;
import 'package:afkcredits/services/local_storage_service.dart' as _i18;
import 'package:afkcredits/services/user_service.dart' as _i5;
import 'package:cloud_firestore/cloud_firestore.dart' as _i6;
import 'package:firebase_auth/firebase_auth.dart' as _i8;
import 'package:flutter/material.dart' as _i21;
import 'package:flutter_secure_storage/flutter_secure_storage.dart' as _i19;
import 'package:logger/logger.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:places_service/src/models/application_models.dart' as _i7;
import 'package:places_service/src/places_service.dart' as _i16;
import 'package:stacked_firebase_auth/stacked_firebase_auth.dart' as _i9;
import 'package:stacked_services/stacked_services.dart' as _i20;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeLogger_0 extends _i1.Fake implements _i2.Logger {}

class _FakeUser_1 extends _i1.Fake implements _i3.User {}

class _FakeUserStatistics_2 extends _i1.Fake implements _i4.UserStatistics {}

class _FakeAFKCreditsAuthenticationResult_3 extends _i1.Fake
    implements _i5.AFKCreditsAuthenticationResult {}

class _FakeFirebaseFirestore_4 extends _i1.Fake
    implements _i6.FirebaseFirestore {}

class _FakeDocumentReference_5 extends _i1.Fake
    implements _i6.DocumentReference {}

class _FakeCollectionReference_6 extends _i1.Fake
    implements _i6.CollectionReference {}

class _FakePlacesLocation_7 extends _i1.Fake implements _i7.PlacesLocation {}

class _FakePlacesDetails_8 extends _i1.Fake implements _i7.PlacesDetails {}

class _FakeFirebaseAuth_9 extends _i1.Fake implements _i8.FirebaseAuth {}

class _FakeFirebaseAuthenticationResult_10 extends _i1.Fake
    implements _i9.FirebaseAuthenticationResult {}

/// A class which mocks [UserService].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserService extends _i1.Mock implements _i5.UserService {
  @override
  _i2.Logger get log =>
      (super.noSuchMethod(Invocation.getter(#log), returnValue: _FakeLogger_0())
          as _i2.Logger);
  @override
  Map<String, _i3.User> get supportedExplorers =>
      (super.noSuchMethod(Invocation.getter(#supportedExplorers),
          returnValue: <String, _i3.User>{}) as Map<String, _i3.User>);
  @override
  set supportedExplorers(Map<String, _i3.User>? _supportedExplorers) => super
      .noSuchMethod(Invocation.setter(#supportedExplorers, _supportedExplorers),
          returnValueForMissingStub: null);
  @override
  Map<String, _i4.UserStatistics> get supportedExplorerStats =>
      (super.noSuchMethod(Invocation.getter(#supportedExplorerStats),
              returnValue: <String, _i4.UserStatistics>{})
          as Map<String, _i4.UserStatistics>);
  @override
  set supportedExplorerStats(
          Map<String, _i4.UserStatistics>? _supportedExplorerStats) =>
      super.noSuchMethod(
          Invocation.setter(#supportedExplorerStats, _supportedExplorerStats),
          returnValueForMissingStub: null);
  @override
  _i3.User get currentUser =>
      (super.noSuchMethod(Invocation.getter(#currentUser),
          returnValue: _FakeUser_1()) as _i3.User);
  @override
  _i4.UserStatistics get currentUserStats =>
      (super.noSuchMethod(Invocation.getter(#currentUserStats),
          returnValue: _FakeUserStatistics_2()) as _i4.UserStatistics);
  @override
  bool get hasLoggedInUser => (super
          .noSuchMethod(Invocation.getter(#hasLoggedInUser), returnValue: false)
      as bool);
  @override
  _i10.UserRole get getUserRole =>
      (super.noSuchMethod(Invocation.getter(#getUserRole),
          returnValue: _i10.UserRole.sponsor) as _i10.UserRole);
  @override
  bool get hasRole =>
      (super.noSuchMethod(Invocation.getter(#hasRole), returnValue: false)
          as bool);
  @override
  List<_i3.User> get supportedExplorersList =>
      (super.noSuchMethod(Invocation.getter(#supportedExplorersList),
          returnValue: <_i3.User>[]) as List<_i3.User>);
  @override
  _i11.Future<void> syncUserAccount(
          {String? uid, bool? fromLocalStorage = false}) =>
      (super.noSuchMethod(
              Invocation.method(#syncUserAccount, [],
                  {#uid: uid, #fromLocalStorage: fromLocalStorage}),
              returnValue: Future<void>.value(),
              returnValueForMissingStub: Future<void>.value())
          as _i11.Future<void>);
  @override
  _i11.Future<_i3.User> createUserAccountFromFirebaseUser(
          {_i10.UserRole? role}) =>
      (super.noSuchMethod(
              Invocation.method(
                  #createUserAccountFromFirebaseUser, [], {#role: role}),
              returnValue: Future<_i3.User>.value(_FakeUser_1()))
          as _i11.Future<_i3.User>);
  @override
  _i11.Future<_i3.User> createUserAccount({_i3.User? user}) =>
      (super.noSuchMethod(
              Invocation.method(#createUserAccount, [], {#user: user}),
              returnValue: Future<_i3.User>.value(_FakeUser_1()))
          as _i11.Future<_i3.User>);
  @override
  _i11.Future<String?> getLocallyLoggedInUserId() =>
      (super.noSuchMethod(Invocation.method(#getLocallyLoggedInUserId, []),
          returnValue: Future<String?>.value()) as _i11.Future<String?>);
  @override
  _i11.Future<_i5.AFKCreditsAuthenticationResult> runLoginLogic(
          {_i12.AuthenticationMethod? method,
          String? emailOrName,
          String? password,
          _i10.UserRole? role}) =>
      (super.noSuchMethod(
              Invocation.method(#runLoginLogic, [], {
                #method: method,
                #emailOrName: emailOrName,
                #password: password,
                #role: role
              }),
              returnValue: Future<_i5.AFKCreditsAuthenticationResult>.value(
                  _FakeAFKCreditsAuthenticationResult_3()))
          as _i11.Future<_i5.AFKCreditsAuthenticationResult>);
  @override
  _i11.Future<_i5.AFKCreditsAuthenticationResult> runCreateAccountLogic(
          {_i12.AuthenticationMethod? method,
          _i10.UserRole? role,
          String? fullName,
          String? email,
          String? password}) =>
      (super.noSuchMethod(
              Invocation.method(#runCreateAccountLogic, [], {
                #method: method,
                #role: role,
                #fullName: fullName,
                #email: email,
                #password: password
              }),
              returnValue: Future<_i5.AFKCreditsAuthenticationResult>.value(
                  _FakeAFKCreditsAuthenticationResult_3()))
          as _i11.Future<_i5.AFKCreditsAuthenticationResult>);
  @override
  bool isSupportedExplorer({String? uid}) => (super.noSuchMethod(
      Invocation.method(#isSupportedExplorer, [], {#uid: uid}),
      returnValue: false) as bool);
  @override
  _i11.Future<dynamic> createExplorerAccount(
          {String? name, String? password}) =>
      (super.noSuchMethod(
          Invocation.method(
              #createExplorerAccount, [], {#name: name, #password: password}),
          returnValue: Future<dynamic>.value()) as _i11.Future<dynamic>);
  @override
  _i11.Future<dynamic> addExplorerToSupportedExplorers({String? uid}) =>
      (super.noSuchMethod(
          Invocation.method(#addExplorerToSupportedExplorers, [], {#uid: uid}),
          returnValue: Future<dynamic>.value()) as _i11.Future<dynamic>);
  @override
  void setupUserDataListeners(
          {_i11.Completer<void>? completer, void Function()? callback}) =>
      super.noSuchMethod(
          Invocation.method(#setupUserDataListeners, [],
              {#completer: completer, #callback: callback}),
          returnValueForMissingStub: null);
  @override
  _i11.Future<void> addExplorerStatsListeners(
          {List<String>? explorerIds, void Function()? callback}) =>
      (super.noSuchMethod(
              Invocation.method(#addExplorerStatsListeners, [],
                  {#explorerIds: explorerIds, #callback: callback}),
              returnValue: Future<void>.value(),
              returnValueForMissingStub: Future<void>.value())
          as _i11.Future<void>);
  @override
  _i11.Future<dynamic> addExplorerStatListener(
          {String? explorerId, void Function()? callback}) =>
      (super.noSuchMethod(
          Invocation.method(#addExplorerStatListener, [],
              {#explorerId: explorerId, #callback: callback}),
          returnValue: Future<dynamic>.value()) as _i11.Future<dynamic>);
  @override
  void removeFromExplorerLists({String? uid}) => super.noSuchMethod(
      Invocation.method(#removeFromExplorerLists, [], {#uid: uid}),
      returnValueForMissingStub: null);
  @override
  List<String> addToSupportedExplorersList({String? uid}) =>
      (super.noSuchMethod(
          Invocation.method(#addToSupportedExplorersList, [], {#uid: uid}),
          returnValue: <String>[]) as List<String>);
  @override
  bool isMatchingPasswords({String? hashedPw, String? stringPw}) =>
      (super.noSuchMethod(
          Invocation.method(#isMatchingPasswords, [],
              {#hashedPw: hashedPw, #stringPw: stringPw}),
          returnValue: false) as bool);
  @override
  String hashPassword(String? pw) => (super
          .noSuchMethod(Invocation.method(#hashPassword, [pw]), returnValue: '')
      as String);
  @override
  _i11.Future<dynamic> updateUserData({_i3.User? user}) =>
      (super.noSuchMethod(Invocation.method(#updateUserData, [], {#user: user}),
          returnValue: Future<dynamic>.value()) as _i11.Future<dynamic>);
  @override
  _i11.Future<dynamic> addSponsorIdToOtherUser(
          {String? otherUsersId, String? sponsorId}) =>
      (super.noSuchMethod(
          Invocation.method(#addSponsorIdToOtherUser, [],
              {#otherUsersId: otherUsersId, #sponsorId: sponsorId}),
          returnValue: Future<dynamic>.value()) as _i11.Future<dynamic>);
  @override
  _i11.Future<dynamic> isUserAlreadyPresent({dynamic name}) => (super
      .noSuchMethod(Invocation.method(#isUserAlreadyPresent, [], {#name: name}),
          returnValue: Future<dynamic>.value()) as _i11.Future<dynamic>);
  @override
  void cancelExplorerStatsListener({String? uid}) => super.noSuchMethod(
      Invocation.method(#cancelExplorerStatsListener, [], {#uid: uid}),
      returnValueForMissingStub: null);
  @override
  _i11.Future<dynamic> handleLogoutEvent() =>
      (super.noSuchMethod(Invocation.method(#handleLogoutEvent, []),
          returnValue: Future<dynamic>.value()) as _i11.Future<dynamic>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [FirestoreApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirestoreApi extends _i1.Mock implements _i13.FirestoreApi {
  @override
  _i2.Logger get log =>
      (super.noSuchMethod(Invocation.getter(#log), returnValue: _FakeLogger_0())
          as _i2.Logger);
  @override
  _i6.FirebaseFirestore get firestoreInstance =>
      (super.noSuchMethod(Invocation.getter(#firestoreInstance),
          returnValue: _FakeFirebaseFirestore_4()) as _i6.FirebaseFirestore);
  @override
  _i11.Future<void> createUser({_i3.User? user, _i4.UserStatistics? stats}) =>
      (super.noSuchMethod(
              Invocation.method(#createUser, [], {#user: user, #stats: stats}),
              returnValue: Future<void>.value(),
              returnValueForMissingStub: Future<void>.value())
          as _i11.Future<void>);
  @override
  _i11.Future<void> createUserInfo({_i3.User? user}) => (super.noSuchMethod(
      Invocation.method(#createUserInfo, [], {#user: user}),
      returnValue: Future<void>.value(),
      returnValueForMissingStub: Future<void>.value()) as _i11.Future<void>);
  @override
  _i11.Future<void> createUserStatistics(
          {String? uid, _i4.UserStatistics? stats}) =>
      (super.noSuchMethod(
              Invocation.method(
                  #createUserStatistics, [], {#uid: uid, #stats: stats}),
              returnValue: Future<void>.value(),
              returnValueForMissingStub: Future<void>.value())
          as _i11.Future<void>);
  @override
  _i6.DocumentReference createUserDocument() =>
      (super.noSuchMethod(Invocation.method(#createUserDocument, []),
          returnValue: _FakeDocumentReference_5()) as _i6.DocumentReference);
  @override
  _i11.Future<_i3.User?> getUser({String? uid}) =>
      (super.noSuchMethod(Invocation.method(#getUser, [], {#uid: uid}),
          returnValue: Future<_i3.User?>.value()) as _i11.Future<_i3.User?>);
  @override
  _i11.Future<_i3.User?> getUserWithName({String? name}) => (super.noSuchMethod(
      Invocation.method(#getUserWithName, [], {#name: name}),
      returnValue: Future<_i3.User?>.value()) as _i11.Future<_i3.User?>);
  @override
  _i11.Future<_i4.UserStatistics> getUserSummaryStatistics({String? uid}) =>
      (super.noSuchMethod(
              Invocation.method(#getUserSummaryStatistics, [], {#uid: uid}),
              returnValue:
                  Future<_i4.UserStatistics>.value(_FakeUserStatistics_2()))
          as _i11.Future<_i4.UserStatistics>);
  @override
  _i11.Stream<_i4.UserStatistics> getUserSummaryStatisticsStream(
          {String? uid}) =>
      (super.noSuchMethod(
          Invocation.method(#getUserSummaryStatisticsStream, [], {#uid: uid}),
          returnValue:
              Stream<_i4.UserStatistics>.empty()) as _i11
          .Stream<_i4.UserStatistics>);
  @override
  _i11.Future<dynamic> updateUserData({_i3.User? user}) =>
      (super.noSuchMethod(Invocation.method(#updateUserData, [], {#user: user}),
          returnValue: Future<dynamic>.value()) as _i11.Future<dynamic>);
  @override
  _i11.Future<dynamic> addSponsorIdToUser({String? uid, String? sponsorId}) =>
      (super.noSuchMethod(
          Invocation.method(
              #addSponsorIdToUser, [], {#uid: uid, #sponsorId: sponsorId}),
          returnValue: Future<dynamic>.value()) as _i11.Future<dynamic>);
  @override
  _i11.Stream<_i3.User> getUserStream({String? uid}) =>
      (super.noSuchMethod(Invocation.method(#getUserStream, [], {#uid: uid}),
          returnValue: Stream<_i3.User>.empty()) as _i11.Stream<_i3.User>);
  @override
  _i11.Stream<List<_i3.User>> getExplorersDataStream({String? uid}) =>
      (super.noSuchMethod(
              Invocation.method(#getExplorersDataStream, [], {#uid: uid}),
              returnValue: Stream<List<_i3.User>>.empty())
          as _i11.Stream<List<_i3.User>>);
  @override
  _i11.Future<List<_i14.PublicUserInfo>> queryExplorers(
          {String? queryString}) =>
      (super.noSuchMethod(
          Invocation.method(#queryExplorers, [], {#queryString: queryString}),
          returnValue: Future<List<_i14.PublicUserInfo>>.value(
              <_i14.PublicUserInfo>[])) as _i11
          .Future<List<_i14.PublicUserInfo>>);
  @override
  _i6.CollectionReference getUserStatisticsCollection({String? uid}) =>
      (super.noSuchMethod(
              Invocation.method(#getUserStatisticsCollection, [], {#uid: uid}),
              returnValue: _FakeCollectionReference_6())
          as _i6.CollectionReference);
  @override
  _i6.DocumentReference getUserSummaryStatisticsDocument({String? uid}) =>
      (super.noSuchMethod(
          Invocation.method(#getUserSummaryStatisticsDocument, [], {#uid: uid}),
          returnValue: _FakeDocumentReference_5()) as _i6.DocumentReference);
  @override
  String toString() => super.toString();
}

/// A class which mocks [EnvironmentService].
///
/// See the documentation for Mockito's code generation for more information.
class MockEnvironmentService extends _i1.Mock
    implements _i15.EnvironmentService {
  @override
  _i2.Logger get log =>
      (super.noSuchMethod(Invocation.getter(#log), returnValue: _FakeLogger_0())
          as _i2.Logger);
  @override
  _i11.Future<dynamic> initialise() =>
      (super.noSuchMethod(Invocation.method(#initialise, []),
          returnValue: Future<dynamic>.value()) as _i11.Future<dynamic>);
  @override
  String getValue(String? key, {bool? verbose = false}) => (super.noSuchMethod(
      Invocation.method(#getValue, [key], {#verbose: verbose}),
      returnValue: '') as String);
  @override
  String toString() => super.toString();
}

/// A class which mocks [PlacesService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPlacesService extends _i1.Mock implements _i16.PlacesService {
  @override
  _i7.PlacesLocation get currentPosition =>
      (super.noSuchMethod(Invocation.getter(#currentPosition),
          returnValue: _FakePlacesLocation_7()) as _i7.PlacesLocation);
  @override
  void initialize({String? apiKey}) =>
      super.noSuchMethod(Invocation.method(#initialize, [], {#apiKey: apiKey}),
          returnValueForMissingStub: null);
  @override
  _i11.Future<List<_i7.PlacesAutoCompleteResult>> getAutoComplete(
          String? input) =>
      (super.noSuchMethod(Invocation.method(#getAutoComplete, [input]),
              returnValue: Future<List<_i7.PlacesAutoCompleteResult>>.value(
                  <_i7.PlacesAutoCompleteResult>[]))
          as _i11.Future<List<_i7.PlacesAutoCompleteResult>>);
  @override
  _i11.Future<_i7.PlacesDetails> getPlaceDetails(String? placeId) =>
      (super.noSuchMethod(Invocation.method(#getPlaceDetails, [placeId]),
              returnValue:
                  Future<_i7.PlacesDetails>.value(_FakePlacesDetails_8()))
          as _i11.Future<_i7.PlacesDetails>);
  @override
  _i11.Future<dynamic> getPlacesAtCurrentLocation() =>
      (super.noSuchMethod(Invocation.method(#getPlacesAtCurrentLocation, []),
          returnValue: Future<dynamic>.value()) as _i11.Future<dynamic>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [FlavorConfigProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockFlavorConfigProvider extends _i1.Mock
    implements _i17.FlavorConfigProvider {
  @override
  _i17.Flavor get flavor => (super.noSuchMethod(Invocation.getter(#flavor),
      returnValue: _i17.Flavor.unknown) as _i17.Flavor);
  @override
  set flavor(_i17.Flavor? _flavor) =>
      super.noSuchMethod(Invocation.setter(#flavor, _flavor),
          returnValueForMissingStub: null);
  @override
  String get appName =>
      (super.noSuchMethod(Invocation.getter(#appName), returnValue: '')
          as String);
  @override
  String get authority =>
      (super.noSuchMethod(Invocation.getter(#authority), returnValue: '')
          as String);
  @override
  String get uripathprepend =>
      (super.noSuchMethod(Invocation.getter(#uripathprepend), returnValue: '')
          as String);
  @override
  void configure(_i17.Flavor? flavorIn) =>
      super.noSuchMethod(Invocation.method(#configure, [flavorIn]),
          returnValueForMissingStub: null);
  @override
  String getTestUserEmail(_i10.UserRole? role) =>
      (super.noSuchMethod(Invocation.method(#getTestUserEmail, [role]),
          returnValue: '') as String);
  @override
  String getTestUserPassword() =>
      (super.noSuchMethod(Invocation.method(#getTestUserPassword, []),
          returnValue: '') as String);
  @override
  String getTestUserId(_i10.UserRole? role) =>
      (super.noSuchMethod(Invocation.method(#getTestUserId, [role]),
          returnValue: '') as String);
  @override
  String toString() => super.toString();
}

/// A class which mocks [LocalStorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalStorageService extends _i1.Mock
    implements _i18.LocalStorageService {
  @override
  _i2.Logger get log =>
      (super.noSuchMethod(Invocation.getter(#log), returnValue: _FakeLogger_0())
          as _i2.Logger);
  @override
  String get authTokenDataKey =>
      (super.noSuchMethod(Invocation.getter(#authTokenDataKey), returnValue: '')
          as String);
  @override
  set authTokenDataKey(String? _authTokenDataKey) => super.noSuchMethod(
      Invocation.setter(#authTokenDataKey, _authTokenDataKey),
      returnValueForMissingStub: null);
  @override
  _i11.Future<dynamic> saveToDisk({String? key, dynamic value}) =>
      (super.noSuchMethod(
          Invocation.method(#saveToDisk, [], {#key: key, #value: value}),
          returnValue: Future<dynamic>.value()) as _i11.Future<dynamic>);
  @override
  _i11.Future<dynamic> deleteFromDisk({String? key}) =>
      (super.noSuchMethod(Invocation.method(#deleteFromDisk, [], {#key: key}),
          returnValue: Future<dynamic>.value()) as _i11.Future<dynamic>);
  @override
  _i11.Future<dynamic> getFromDisk({String? key}) =>
      (super.noSuchMethod(Invocation.method(#getFromDisk, [], {#key: key}),
          returnValue: Future<dynamic>.value()) as _i11.Future<dynamic>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [FlutterSecureStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockFlutterSecureStorage extends _i1.Mock
    implements _i19.FlutterSecureStorage {
  @override
  _i11.Future<void> write(
          {String? key,
          String? value,
          _i19.IOSOptions? iOptions = _i19.IOSOptions.defaultOptions,
          _i19.AndroidOptions? aOptions,
          _i19.LinuxOptions? lOptions}) =>
      (super.noSuchMethod(
              Invocation.method(#write, [], {
                #key: key,
                #value: value,
                #iOptions: iOptions,
                #aOptions: aOptions,
                #lOptions: lOptions
              }),
              returnValue: Future<void>.value(),
              returnValueForMissingStub: Future<void>.value())
          as _i11.Future<void>);
  @override
  _i11.Future<String?> read(
          {String? key,
          _i19.IOSOptions? iOptions = _i19.IOSOptions.defaultOptions,
          _i19.AndroidOptions? aOptions,
          _i19.LinuxOptions? lOptions}) =>
      (super.noSuchMethod(
          Invocation.method(#read, [], {
            #key: key,
            #iOptions: iOptions,
            #aOptions: aOptions,
            #lOptions: lOptions
          }),
          returnValue: Future<String?>.value()) as _i11.Future<String?>);
  @override
  _i11.Future<bool> containsKey(
          {String? key,
          _i19.IOSOptions? iOptions = _i19.IOSOptions.defaultOptions,
          _i19.AndroidOptions? aOptions,
          _i19.LinuxOptions? lOptions}) =>
      (super.noSuchMethod(
          Invocation.method(#containsKey, [], {
            #key: key,
            #iOptions: iOptions,
            #aOptions: aOptions,
            #lOptions: lOptions
          }),
          returnValue: Future<bool>.value(false)) as _i11.Future<bool>);
  @override
  _i11.Future<void> delete(
          {String? key,
          _i19.IOSOptions? iOptions = _i19.IOSOptions.defaultOptions,
          _i19.AndroidOptions? aOptions,
          _i19.LinuxOptions? lOptions}) =>
      (super.noSuchMethod(
              Invocation.method(#delete, [], {
                #key: key,
                #iOptions: iOptions,
                #aOptions: aOptions,
                #lOptions: lOptions
              }),
              returnValue: Future<void>.value(),
              returnValueForMissingStub: Future<void>.value())
          as _i11.Future<void>);
  @override
  _i11.Future<Map<String, String>> readAll(
          {_i19.IOSOptions? iOptions = _i19.IOSOptions.defaultOptions,
          _i19.AndroidOptions? aOptions,
          _i19.LinuxOptions? lOptions}) =>
      (super.noSuchMethod(
              Invocation.method(#readAll, [], {
                #iOptions: iOptions,
                #aOptions: aOptions,
                #lOptions: lOptions
              }),
              returnValue:
                  Future<Map<String, String>>.value(<String, String>{}))
          as _i11.Future<Map<String, String>>);
  @override
  _i11.Future<void> deleteAll(
          {_i19.IOSOptions? iOptions = _i19.IOSOptions.defaultOptions,
          _i19.AndroidOptions? aOptions,
          _i19.LinuxOptions? lOptions}) =>
      (super.noSuchMethod(
              Invocation.method(#deleteAll, [], {
                #iOptions: iOptions,
                #aOptions: aOptions,
                #lOptions: lOptions
              }),
              returnValue: Future<void>.value(),
              returnValueForMissingStub: Future<void>.value())
          as _i11.Future<void>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [NavigationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNavigationService extends _i1.Mock implements _i20.NavigationService {
  @override
  String get previousRoute =>
      (super.noSuchMethod(Invocation.getter(#previousRoute), returnValue: '')
          as String);
  @override
  String get currentRoute =>
      (super.noSuchMethod(Invocation.getter(#currentRoute), returnValue: '')
          as String);
  @override
  _i21.GlobalKey<_i21.NavigatorState>? nestedNavigationKey(int? index) =>
      (super.noSuchMethod(Invocation.method(#nestedNavigationKey, [index]))
          as _i21.GlobalKey<_i21.NavigatorState>?);
  @override
  void config(
          {bool? enableLog,
          bool? defaultPopGesture,
          bool? defaultOpaqueRoute,
          Duration? defaultDurationTransition,
          bool? defaultGlobalState,
          String? defaultTransition}) =>
      super.noSuchMethod(
          Invocation.method(#config, [], {
            #enableLog: enableLog,
            #defaultPopGesture: defaultPopGesture,
            #defaultOpaqueRoute: defaultOpaqueRoute,
            #defaultDurationTransition: defaultDurationTransition,
            #defaultGlobalState: defaultGlobalState,
            #defaultTransition: defaultTransition
          }),
          returnValueForMissingStub: null);
  @override
  _i11.Future<T?>? navigateWithTransition<T>(_i21.Widget? page,
          {bool? opaque,
          String? transition = r'',
          Duration? duration,
          bool? popGesture,
          int? id,
          _i21.Curve? curve,
          _i20.Bindings? binding,
          bool? fullscreenDialog = false,
          bool? preventDuplicates = true,
          _i20.Transition? transitionClass}) =>
      (super.noSuchMethod(Invocation.method(#navigateWithTransition, [
        page
      ], {
        #opaque: opaque,
        #transition: transition,
        #duration: duration,
        #popGesture: popGesture,
        #id: id,
        #curve: curve,
        #binding: binding,
        #fullscreenDialog: fullscreenDialog,
        #preventDuplicates: preventDuplicates,
        #transitionClass: transitionClass
      })) as _i11.Future<T?>?);
  @override
  _i11.Future<T?>? replaceWithTransition<T>(_i21.Widget? page,
          {bool? opaque,
          String? transition = r'',
          Duration? duration,
          bool? popGesture,
          int? id,
          _i21.Curve? curve,
          _i20.Bindings? binding,
          bool? fullscreenDialog = false,
          bool? preventDuplicates = true,
          _i20.Transition? transitionClass}) =>
      (super.noSuchMethod(Invocation.method(#replaceWithTransition, [
        page
      ], {
        #opaque: opaque,
        #transition: transition,
        #duration: duration,
        #popGesture: popGesture,
        #id: id,
        #curve: curve,
        #binding: binding,
        #fullscreenDialog: fullscreenDialog,
        #preventDuplicates: preventDuplicates,
        #transitionClass: transitionClass
      })) as _i11.Future<T?>?);
  @override
  bool back<T>({T? result, int? id}) => (super.noSuchMethod(
      Invocation.method(#back, [], {#result: result, #id: id}),
      returnValue: false) as bool);
  @override
  void popUntil(_i21.RoutePredicate? predicate) =>
      super.noSuchMethod(Invocation.method(#popUntil, [predicate]),
          returnValueForMissingStub: null);
  @override
  void popRepeated(int? popTimes) =>
      super.noSuchMethod(Invocation.method(#popRepeated, [popTimes]),
          returnValueForMissingStub: null);
  @override
  _i11.Future<T?>? navigateTo<T>(String? routeName,
          {dynamic arguments,
          int? id,
          bool? preventDuplicates = true,
          Map<String, String>? parameters}) =>
      (super.noSuchMethod(Invocation.method(#navigateTo, [
        routeName
      ], {
        #arguments: arguments,
        #id: id,
        #preventDuplicates: preventDuplicates,
        #parameters: parameters
      })) as _i11.Future<T?>?);
  @override
  _i11.Future<T?>? navigateToView<T>(_i21.Widget? view,
          {dynamic arguments,
          int? id,
          bool? opaque,
          _i21.Curve? curve,
          _i20.Bindings? binding,
          Duration? duration,
          bool? fullscreenDialog = false,
          bool? popGesture,
          bool? preventDuplicates = true,
          _i20.Transition? transition}) =>
      (super.noSuchMethod(Invocation.method(#navigateToView, [
        view
      ], {
        #arguments: arguments,
        #id: id,
        #opaque: opaque,
        #curve: curve,
        #binding: binding,
        #duration: duration,
        #fullscreenDialog: fullscreenDialog,
        #popGesture: popGesture,
        #preventDuplicates: preventDuplicates,
        #transition: transition
      })) as _i11.Future<T?>?);
  @override
  _i11.Future<T?>? replaceWith<T>(String? routeName,
          {dynamic arguments,
          int? id,
          bool? preventDuplicates = true,
          Map<String, String>? parameters}) =>
      (super.noSuchMethod(Invocation.method(#replaceWith, [
        routeName
      ], {
        #arguments: arguments,
        #id: id,
        #preventDuplicates: preventDuplicates,
        #parameters: parameters
      })) as _i11.Future<T?>?);
  @override
  _i11.Future<T?>? clearStackAndShow<T>(String? routeName,
          {dynamic arguments, int? id, Map<String, String>? parameters}) =>
      (super.noSuchMethod(Invocation.method(#clearStackAndShow, [
        routeName
      ], {
        #arguments: arguments,
        #id: id,
        #parameters: parameters
      })) as _i11.Future<T?>?);
  @override
  _i11.Future<T?>? clearTillFirstAndShow<T>(String? routeName,
          {dynamic arguments,
          int? id,
          bool? preventDuplicates = true,
          Map<String, String>? parameters}) =>
      (super.noSuchMethod(Invocation.method(#clearTillFirstAndShow, [
        routeName
      ], {
        #arguments: arguments,
        #id: id,
        #preventDuplicates: preventDuplicates,
        #parameters: parameters
      })) as _i11.Future<T?>?);
  @override
  _i11.Future<T?>? clearTillFirstAndShowView<T>(_i21.Widget? view,
          {dynamic arguments, int? id}) =>
      (super.noSuchMethod(Invocation.method(#clearTillFirstAndShowView, [view],
          {#arguments: arguments, #id: id})) as _i11.Future<T?>?);
  @override
  _i11.Future<T?>? pushNamedAndRemoveUntil<T>(String? routeName,
          {_i21.RoutePredicate? predicate, dynamic arguments, int? id}) =>
      (super.noSuchMethod(Invocation.method(#pushNamedAndRemoveUntil, [
        routeName
      ], {
        #predicate: predicate,
        #arguments: arguments,
        #id: id
      })) as _i11.Future<T?>?);
  @override
  String toString() => super.toString();
}

/// A class which mocks [DialogService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDialogService extends _i1.Mock implements _i20.DialogService {
  @override
  void registerCustomDialogBuilders(
          Map<dynamic, _i20.DialogBuilder>? builders) =>
      super.noSuchMethod(
          Invocation.method(#registerCustomDialogBuilders, [builders]),
          returnValueForMissingStub: null);
  @override
  void registerCustomDialogBuilder(
          {dynamic variant,
          _i21.Widget Function(_i21.BuildContext, _i20.DialogRequest<dynamic>,
                  dynamic Function(_i20.DialogResponse<dynamic>))?
              builder}) =>
      super.noSuchMethod(
          Invocation.method(#registerCustomDialogBuilder, [],
              {#variant: variant, #builder: builder}),
          returnValueForMissingStub: null);
  @override
  _i11.Future<_i20.DialogResponse<dynamic>?> showDialog(
          {String? title,
          String? description,
          String? cancelTitle,
          _i22.Color? cancelTitleColor,
          String? buttonTitle = r'Ok',
          _i22.Color? buttonTitleColor,
          bool? barrierDismissible = false,
          _i20.DialogPlatform? dialogPlatform}) =>
      (super.noSuchMethod(
              Invocation.method(#showDialog, [], {
                #title: title,
                #description: description,
                #cancelTitle: cancelTitle,
                #cancelTitleColor: cancelTitleColor,
                #buttonTitle: buttonTitle,
                #buttonTitleColor: buttonTitleColor,
                #barrierDismissible: barrierDismissible,
                #dialogPlatform: dialogPlatform
              }),
              returnValue: Future<_i20.DialogResponse<dynamic>?>.value())
          as _i11.Future<_i20.DialogResponse<dynamic>?>);
  @override
  _i11.Future<_i20.DialogResponse<T>?> showCustomDialog<T, R>(
          {dynamic variant,
          String? title,
          String? description,
          bool? hasImage = false,
          String? imageUrl,
          bool? showIconInMainButton = false,
          String? mainButtonTitle,
          bool? showIconInSecondaryButton = false,
          String? secondaryButtonTitle,
          bool? showIconInAdditionalButton = false,
          String? additionalButtonTitle,
          bool? takesInput = false,
          _i22.Color? barrierColor = const _i22.Color(2315255808),
          bool? barrierDismissible = false,
          String? barrierLabel = r'',
          dynamic customData,
          R? data}) =>
      (super.noSuchMethod(
              Invocation.method(#showCustomDialog, [], {
                #variant: variant,
                #title: title,
                #description: description,
                #hasImage: hasImage,
                #imageUrl: imageUrl,
                #showIconInMainButton: showIconInMainButton,
                #mainButtonTitle: mainButtonTitle,
                #showIconInSecondaryButton: showIconInSecondaryButton,
                #secondaryButtonTitle: secondaryButtonTitle,
                #showIconInAdditionalButton: showIconInAdditionalButton,
                #additionalButtonTitle: additionalButtonTitle,
                #takesInput: takesInput,
                #barrierColor: barrierColor,
                #barrierDismissible: barrierDismissible,
                #barrierLabel: barrierLabel,
                #customData: customData,
                #data: data
              }),
              returnValue: Future<_i20.DialogResponse<T>?>.value())
          as _i11.Future<_i20.DialogResponse<T>?>);
  @override
  _i11.Future<_i20.DialogResponse<dynamic>?> showConfirmationDialog(
          {String? title,
          String? description,
          String? cancelTitle = r'Cancel',
          String? confirmationTitle = r'Ok',
          bool? barrierDismissible = false,
          _i20.DialogPlatform? dialogPlatform}) =>
      (super.noSuchMethod(
              Invocation.method(#showConfirmationDialog, [], {
                #title: title,
                #description: description,
                #cancelTitle: cancelTitle,
                #confirmationTitle: confirmationTitle,
                #barrierDismissible: barrierDismissible,
                #dialogPlatform: dialogPlatform
              }),
              returnValue: Future<_i20.DialogResponse<dynamic>?>.value())
          as _i11.Future<_i20.DialogResponse<dynamic>?>);
  @override
  void completeDialog(_i20.DialogResponse<dynamic>? response) =>
      super.noSuchMethod(Invocation.method(#completeDialog, [response]),
          returnValueForMissingStub: null);
  @override
  String toString() => super.toString();
}

/// A class which mocks [FirebaseAuthenticationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirebaseAuthenticationService extends _i1.Mock
    implements _i9.FirebaseAuthenticationService {
  @override
  _i8.FirebaseAuth get firebaseAuth =>
      (super.noSuchMethod(Invocation.getter(#firebaseAuth),
          returnValue: _FakeFirebaseAuth_9()) as _i8.FirebaseAuth);
  @override
  bool get hasUser =>
      (super.noSuchMethod(Invocation.getter(#hasUser), returnValue: false)
          as bool);
  @override
  _i11.Stream<_i8.User?> get authStateChanges =>
      (super.noSuchMethod(Invocation.getter(#authStateChanges),
          returnValue: Stream<_i8.User?>.empty()) as _i11.Stream<_i8.User?>);
  @override
  _i11.Future<bool> emailExists(String? email) =>
      (super.noSuchMethod(Invocation.method(#emailExists, [email]),
          returnValue: Future<bool>.value(false)) as _i11.Future<bool>);
  @override
  _i11.Future<_i9.FirebaseAuthenticationResult> signInWithGoogle() =>
      (super.noSuchMethod(Invocation.method(#signInWithGoogle, []),
              returnValue: Future<_i9.FirebaseAuthenticationResult>.value(
                  _FakeFirebaseAuthenticationResult_10()))
          as _i11.Future<_i9.FirebaseAuthenticationResult>);
  @override
  _i11.Future<bool> isAppleSignInAvailable() =>
      (super.noSuchMethod(Invocation.method(#isAppleSignInAvailable, []),
          returnValue: Future<bool>.value(false)) as _i11.Future<bool>);
  @override
  _i11.Future<_i9.FirebaseAuthenticationResult> signInWithApple(
          {String? appleRedirectUri, String? appleClientId}) =>
      (super.noSuchMethod(
              Invocation.method(#signInWithApple, [], {
                #appleRedirectUri: appleRedirectUri,
                #appleClientId: appleClientId
              }),
              returnValue: Future<_i9.FirebaseAuthenticationResult>.value(
                  _FakeFirebaseAuthenticationResult_10()))
          as _i11.Future<_i9.FirebaseAuthenticationResult>);
  @override
  _i11.Future<_i9.FirebaseAuthenticationResult> loginAnonymously() =>
      (super.noSuchMethod(Invocation.method(#loginAnonymously, []),
              returnValue: Future<_i9.FirebaseAuthenticationResult>.value(
                  _FakeFirebaseAuthenticationResult_10()))
          as _i11.Future<_i9.FirebaseAuthenticationResult>);
  @override
  _i11.Future<_i9.FirebaseAuthenticationResult> loginWithEmail(
          {String? email, String? password}) =>
      (super.noSuchMethod(
              Invocation.method(
                  #loginWithEmail, [], {#email: email, #password: password}),
              returnValue: Future<_i9.FirebaseAuthenticationResult>.value(
                  _FakeFirebaseAuthenticationResult_10()))
          as _i11.Future<_i9.FirebaseAuthenticationResult>);
  @override
  _i11.Future<_i9.FirebaseAuthenticationResult> createAccountWithEmail(
          {String? email, String? password}) =>
      (super.noSuchMethod(
              Invocation.method(#createAccountWithEmail, [],
                  {#email: email, #password: password}),
              returnValue: Future<_i9.FirebaseAuthenticationResult>.value(
                  _FakeFirebaseAuthenticationResult_10()))
          as _i11.Future<_i9.FirebaseAuthenticationResult>);
  @override
  _i11.Future<dynamic> logout() =>
      (super.noSuchMethod(Invocation.method(#logout, []),
          returnValue: Future<dynamic>.value()) as _i11.Future<dynamic>);
  @override
  _i11.Future<dynamic> sendResetPasswordLink(String? email) =>
      (super.noSuchMethod(Invocation.method(#sendResetPasswordLink, [email]),
          returnValue: Future<dynamic>.value()) as _i11.Future<dynamic>);
  @override
  _i11.Future<dynamic> validatePassword(String? password) =>
      (super.noSuchMethod(Invocation.method(#validatePassword, [password]),
          returnValue: Future<dynamic>.value()) as _i11.Future<dynamic>);
  @override
  _i11.Future<dynamic> updatePassword(String? password) =>
      (super.noSuchMethod(Invocation.method(#updatePassword, [password]),
          returnValue: Future<dynamic>.value()) as _i11.Future<dynamic>);
  @override
  _i11.Future<dynamic> updateEmail(String? email) =>
      (super.noSuchMethod(Invocation.method(#updateEmail, [email]),
          returnValue: Future<dynamic>.value()) as _i11.Future<dynamic>);
  @override
  String generateNonce([int? length = 32]) =>
      (super.noSuchMethod(Invocation.method(#generateNonce, [length]),
          returnValue: '') as String);
  @override
  String sha256ofString(String? input) =>
      (super.noSuchMethod(Invocation.method(#sha256ofString, [input]),
          returnValue: '') as String);
  @override
  String toString() => super.toString();
}
