// Mocks generated by Mockito 5.0.14 from annotations
// in afkcredits/test/helpers/test_helpers.dart.
// Do not manually edit this file.

import 'dart:async' as _i18;
import 'dart:ui' as _i41;

import 'package:afkcredits/apis/firestore_api.dart' as _i21;
import 'package:afkcredits/datamodels/payments/money_transfer.dart' as _i24;
import 'package:afkcredits/datamodels/payments/money_transfer_query_config.dart'
    as _i25;
import 'package:afkcredits/datamodels/places/places.dart' as _i34;
import 'package:afkcredits/datamodels/quests/active_quests/activated_quest.dart'
    as _i12;
import 'package:afkcredits/datamodels/quests/completed_quest/completed_quest.dart'
    as _i22;
import 'package:afkcredits/datamodels/quests/markers/marker.dart' as _i13;
import 'package:afkcredits/datamodels/quests/quest.dart' as _i10;
import 'package:afkcredits/datamodels/users/favorite_places/user_fav_places.dart'
    as _i19;
import 'package:afkcredits/datamodels/users/public_info/public_user_info.dart'
    as _i23;
import 'package:afkcredits/datamodels/users/statistics/user_statistics.dart'
    as _i3;
import 'package:afkcredits/datamodels/users/user.dart' as _i2;
import 'package:afkcredits/enums/authentication_method.dart' as _i20;
import 'package:afkcredits/enums/user_role.dart' as _i17;
import 'package:afkcredits/flavor_config.dart' as _i28;
import 'package:afkcredits/services/environment_services.dart' as _i26;
import 'package:afkcredits/services/geolocation/geolocation_service.dart'
    as _i33;
import 'package:afkcredits/services/layout/layout_service.dart' as _i31;
import 'package:afkcredits/services/local_storage_service.dart' as _i29;
import 'package:afkcredits/services/markers/marker_service.dart' as _i37;
import 'package:afkcredits/services/payments/transfers_history_service.dart'
    as _i32;
import 'package:afkcredits/services/qrcodes/qrcode_service.dart' as _i38;
import 'package:afkcredits/services/quests/quest_qrcode_scan_result.dart'
    as _i11;
import 'package:afkcredits/services/quests/quest_service.dart' as _i35;
import 'package:afkcredits/services/quests/stopwatch_service.dart' as _i36;
import 'package:afkcredits/services/users/afkcredits_authentication_result_service.dart'
    as _i4;
import 'package:afkcredits/services/users/user_service.dart' as _i16;
import 'package:cloud_firestore/cloud_firestore.dart' as _i5;
import 'package:firebase_auth/firebase_auth.dart' as _i14;
import 'package:flutter/material.dart' as _i40;
import 'package:flutter_secure_storage/flutter_secure_storage.dart' as _i30;
import 'package:geolocator/geolocator.dart' as _i8;
import 'package:google_maps_flutter/google_maps_flutter.dart' as _i9;
import 'package:mockito/mockito.dart' as _i1;
import 'package:places_service/src/models/application_models.dart' as _i6;
import 'package:places_service/src/places_service.dart' as _i27;
import 'package:rxdart/rxdart.dart' as _i7;
import 'package:stacked_firebase_auth/stacked_firebase_auth.dart' as _i15;
import 'package:stacked_services/stacked_services.dart' as _i39;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeUser_0 extends _i1.Fake implements _i2.User {}

class _FakeUserStatistics_1 extends _i1.Fake implements _i3.UserStatistics {}

class _FakeAFKCreditsAuthenticationResultService_2 extends _i1.Fake
    implements _i4.AFKCreditsAuthenticationResultService {}

class _FakeFirebaseFirestore_3 extends _i1.Fake
    implements _i5.FirebaseFirestore {}

class _FakeDocumentReference_4 extends _i1.Fake
    implements _i5.DocumentReference {}

class _FakePlacesLocation_5 extends _i1.Fake implements _i6.PlacesLocation {}

class _FakePlacesDetails_6 extends _i1.Fake implements _i6.PlacesDetails {}

class _FakeBehaviorSubject_7<T> extends _i1.Fake
    implements _i7.BehaviorSubject<T> {}

class _FakePosition_8 extends _i1.Fake implements _i8.Position {}

class _FakeCameraPosition_9 extends _i1.Fake implements _i9.CameraPosition {}

class _FakeQuest_10 extends _i1.Fake implements _i10.Quest {}

class _FakeQuestQRCodeScanResult_11 extends _i1.Fake
    implements _i11.QuestQRCodeScanResult {}

class _FakeActivatedQuest_12 extends _i1.Fake implements _i12.ActivatedQuest {}

class _FakeAFKMarker_13 extends _i1.Fake implements _i13.AFKMarker {}

class _FakeFirebaseAuth_14 extends _i1.Fake implements _i14.FirebaseAuth {}

class _FakeFirebaseAuthenticationResult_15 extends _i1.Fake
    implements _i15.FirebaseAuthenticationResult {}

/// A class which mocks [UserService].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserService extends _i1.Mock implements _i16.UserService {
  @override
  Map<String, _i2.User> get supportedExplorers =>
      (super.noSuchMethod(Invocation.getter(#supportedExplorers),
          returnValue: <String, _i2.User>{}) as Map<String, _i2.User>);
  @override
  set supportedExplorers(Map<String, _i2.User>? _supportedExplorers) => super
      .noSuchMethod(Invocation.setter(#supportedExplorers, _supportedExplorers),
          returnValueForMissingStub: null);
  @override
  Map<String, _i3.UserStatistics> get supportedExplorerStats =>
      (super.noSuchMethod(Invocation.getter(#supportedExplorerStats),
              returnValue: <String, _i3.UserStatistics>{})
          as Map<String, _i3.UserStatistics>);
  @override
  set supportedExplorerStats(
          Map<String, _i3.UserStatistics>? _supportedExplorerStats) =>
      super.noSuchMethod(
          Invocation.setter(#supportedExplorerStats, _supportedExplorerStats),
          returnValueForMissingStub: null);
  @override
  _i2.User get currentUser =>
      (super.noSuchMethod(Invocation.getter(#currentUser),
          returnValue: _FakeUser_0()) as _i2.User);
  @override
  _i3.UserStatistics get currentUserStats =>
      (super.noSuchMethod(Invocation.getter(#currentUserStats),
          returnValue: _FakeUserStatistics_1()) as _i3.UserStatistics);
  @override
  bool get hasLoggedInUser => (super
          .noSuchMethod(Invocation.getter(#hasLoggedInUser), returnValue: false)
      as bool);
  @override
  _i17.UserRole get getUserRole =>
      (super.noSuchMethod(Invocation.getter(#getUserRole),
          returnValue: _i17.UserRole.sponsor) as _i17.UserRole);
  @override
  bool get hasRole =>
      (super.noSuchMethod(Invocation.getter(#hasRole), returnValue: false)
          as bool);
  @override
  List<_i2.User> get supportedExplorersList =>
      (super.noSuchMethod(Invocation.getter(#supportedExplorersList),
          returnValue: <_i2.User>[]) as List<_i2.User>);
  @override
  _i18.Future<void> syncUserAccount(
          {String? uid, bool? fromLocalStorage = false}) =>
      (super.noSuchMethod(
              Invocation.method(#syncUserAccount, [],
                  {#uid: uid, #fromLocalStorage: fromLocalStorage}),
              returnValue: Future<void>.value(),
              returnValueForMissingStub: Future<void>.value())
          as _i18.Future<void>);
  @override
  _i18.Future<_i2.User> createUserAccountFromFirebaseUser(
          {_i17.UserRole? role}) =>
      (super.noSuchMethod(
              Invocation.method(
                  #createUserAccountFromFirebaseUser, [], {#role: role}),
              returnValue: Future<_i2.User>.value(_FakeUser_0()))
          as _i18.Future<_i2.User>);
  @override
  _i18.Future<_i2.User> createUserAccount({_i2.User? user}) =>
      (super.noSuchMethod(
              Invocation.method(#createUserAccount, [], {#user: user}),
              returnValue: Future<_i2.User>.value(_FakeUser_0()))
          as _i18.Future<_i2.User>);
  @override
  _i18.Future<void> createUserFavouritePlaces(
          {String? userId, _i19.UserFavPlaces? favouritePlaces}) =>
      (super.noSuchMethod(
              Invocation.method(#createUserFavouritePlaces, [],
                  {#userId: userId, #favouritePlaces: favouritePlaces}),
              returnValue: Future<void>.value(),
              returnValueForMissingStub: Future<void>.value())
          as _i18.Future<void>);
  @override
  _i18.Future<List<_i19.UserFavPlaces>?> getUserFavouritePlaces(
          {String? userId}) =>
      (super.noSuchMethod(
              Invocation.method(#getUserFavouritePlaces, [], {#userId: userId}),
              returnValue: Future<List<_i19.UserFavPlaces>?>.value())
          as _i18.Future<List<_i19.UserFavPlaces>?>);
  @override
  _i18.Future<String?> getLocallyLoggedInUserId() =>
      (super.noSuchMethod(Invocation.method(#getLocallyLoggedInUserId, []),
          returnValue: Future<String?>.value()) as _i18.Future<String?>);
  @override
  _i18.Future<_i4.AFKCreditsAuthenticationResultService> runLoginLogic(
          {_i20.AuthenticationMethod? method,
          String? emailOrName,
          String? password,
          _i17.UserRole? role}) =>
      (super.noSuchMethod(
          Invocation.method(#runLoginLogic, [], {
            #method: method,
            #emailOrName: emailOrName,
            #password: password,
            #role: role
          }),
          returnValue: Future<_i4.AFKCreditsAuthenticationResultService>.value(
              _FakeAFKCreditsAuthenticationResultService_2())) as _i18
          .Future<_i4.AFKCreditsAuthenticationResultService>);
  @override
  _i18.Future<_i4.AFKCreditsAuthenticationResultService> runCreateAccountLogic(
          {_i20.AuthenticationMethod? method,
          _i17.UserRole? role,
          String? fullName,
          String? email,
          String? password}) =>
      (super.noSuchMethod(
          Invocation.method(#runCreateAccountLogic, [], {
            #method: method,
            #role: role,
            #fullName: fullName,
            #email: email,
            #password: password
          }),
          returnValue: Future<_i4.AFKCreditsAuthenticationResultService>.value(
              _FakeAFKCreditsAuthenticationResultService_2())) as _i18
          .Future<_i4.AFKCreditsAuthenticationResultService>);
  @override
  bool isSupportedExplorer({String? uid}) => (super.noSuchMethod(
      Invocation.method(#isSupportedExplorer, [], {#uid: uid}),
      returnValue: false) as bool);
  @override
  _i18.Future<dynamic> createExplorerAccount(
          {String? name, String? password}) =>
      (super.noSuchMethod(
          Invocation.method(
              #createExplorerAccount, [], {#name: name, #password: password}),
          returnValue: Future<dynamic>.value()) as _i18.Future<dynamic>);
  @override
  _i18.Future<dynamic> addExplorerToSupportedExplorers({String? uid}) =>
      (super.noSuchMethod(
          Invocation.method(#addExplorerToSupportedExplorers, [], {#uid: uid}),
          returnValue: Future<dynamic>.value()) as _i18.Future<dynamic>);
  @override
  void setupUserDataListeners(
          {_i18.Completer<void>? completer, void Function()? callback}) =>
      super.noSuchMethod(
          Invocation.method(#setupUserDataListeners, [],
              {#completer: completer, #callback: callback}),
          returnValueForMissingStub: null);
  @override
  _i18.Future<void> addExplorerStatsListeners(
          {List<String>? explorerIds, void Function()? callback}) =>
      (super.noSuchMethod(
              Invocation.method(#addExplorerStatsListeners, [],
                  {#explorerIds: explorerIds, #callback: callback}),
              returnValue: Future<void>.value(),
              returnValueForMissingStub: Future<void>.value())
          as _i18.Future<void>);
  @override
  _i18.Future<dynamic> addExplorerStatListener(
          {String? explorerId, void Function()? callback}) =>
      (super.noSuchMethod(
          Invocation.method(#addExplorerStatListener, [],
              {#explorerId: explorerId, #callback: callback}),
          returnValue: Future<dynamic>.value()) as _i18.Future<dynamic>);
  @override
  void removeFromExplorerLists({String? uid}) => super.noSuchMethod(
      Invocation.method(#removeFromExplorerLists, [], {#uid: uid}),
      returnValueForMissingStub: null);
  @override
  List<String> addToSupportedExplorersList({String? uid}) =>
      (super.noSuchMethod(
          Invocation.method(#addToSupportedExplorersList, [], {#uid: uid}),
          returnValue: <String>[]) as List<String>);
  @override
  bool isMatchingPasswords({String? hashedPw, String? stringPw}) =>
      (super.noSuchMethod(
          Invocation.method(#isMatchingPasswords, [],
              {#hashedPw: hashedPw, #stringPw: stringPw}),
          returnValue: false) as bool);
  @override
  String hashPassword(String? pw) => (super
          .noSuchMethod(Invocation.method(#hashPassword, [pw]), returnValue: '')
      as String);
  @override
  _i18.Future<dynamic> updateUserData({_i2.User? user}) =>
      (super.noSuchMethod(Invocation.method(#updateUserData, [], {#user: user}),
          returnValue: Future<dynamic>.value()) as _i18.Future<dynamic>);
  @override
  _i18.Future<dynamic> addSponsorIdToOtherUser(
          {String? otherUsersId, String? sponsorId}) =>
      (super.noSuchMethod(
          Invocation.method(#addSponsorIdToOtherUser, [],
              {#otherUsersId: otherUsersId, #sponsorId: sponsorId}),
          returnValue: Future<dynamic>.value()) as _i18.Future<dynamic>);
  @override
  _i18.Future<dynamic> isUserAlreadyPresent({dynamic name}) => (super
      .noSuchMethod(Invocation.method(#isUserAlreadyPresent, [], {#name: name}),
          returnValue: Future<dynamic>.value()) as _i18.Future<dynamic>);
  @override
  void cancelExplorerStatsListener({String? uid}) => super.noSuchMethod(
      Invocation.method(#cancelExplorerStatsListener, [], {#uid: uid}),
      returnValueForMissingStub: null);
  @override
  _i18.Future<dynamic> handleLogoutEvent() =>
      (super.noSuchMethod(Invocation.method(#handleLogoutEvent, []),
          returnValue: Future<dynamic>.value()) as _i18.Future<dynamic>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [FirestoreApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirestoreApi extends _i1.Mock implements _i21.FirestoreApi {
  @override
  _i5.FirebaseFirestore get firestoreInstance =>
      (super.noSuchMethod(Invocation.getter(#firestoreInstance),
          returnValue: _FakeFirebaseFirestore_3()) as _i5.FirebaseFirestore);
  @override
  _i18.Future<void> createUser({_i2.User? user, _i3.UserStatistics? stats}) =>
      (super.noSuchMethod(
              Invocation.method(#createUser, [], {#user: user, #stats: stats}),
              returnValue: Future<void>.value(),
              returnValueForMissingStub: Future<void>.value())
          as _i18.Future<void>);
  @override
  _i18.Future<void> createUserInfo({_i2.User? user}) => (super.noSuchMethod(
      Invocation.method(#createUserInfo, [], {#user: user}),
      returnValue: Future<void>.value(),
      returnValueForMissingStub: Future<void>.value()) as _i18.Future<void>);
  @override
  _i18.Future<void> createUserStatistics(
          {String? uid, _i3.UserStatistics? stats}) =>
      (super.noSuchMethod(
              Invocation.method(
                  #createUserStatistics, [], {#uid: uid, #stats: stats}),
              returnValue: Future<void>.value(),
              returnValueForMissingStub: Future<void>.value())
          as _i18.Future<void>);
  @override
  _i18.Future<void> createUserFavouritePlaces(
          {dynamic userId, _i19.UserFavPlaces? favouritePlaces}) =>
      (super.noSuchMethod(
              Invocation.method(#createUserFavouritePlaces, [],
                  {#userId: userId, #favouritePlaces: favouritePlaces}),
              returnValue: Future<void>.value(),
              returnValueForMissingStub: Future<void>.value())
          as _i18.Future<void>);
  @override
  _i18.Future<void> createUserCompletedQuest(
          {dynamic userId, _i22.CompletedQuest? completedQuest}) =>
      (super.noSuchMethod(
              Invocation.method(#createUserCompletedQuest, [],
                  {#userId: userId, #completedQuest: completedQuest}),
              returnValue: Future<void>.value(),
              returnValueForMissingStub: Future<void>.value())
          as _i18.Future<void>);
  @override
  _i18.Future<void> createMarkers({_i13.AFKMarker? markers}) =>
      (super.noSuchMethod(
              Invocation.method(#createMarkers, [], {#markers: markers}),
              returnValue: Future<void>.value(),
              returnValueForMissingStub: Future<void>.value())
          as _i18.Future<void>);
  @override
  _i5.DocumentReference createUserDocument() =>
      (super.noSuchMethod(Invocation.method(#createUserDocument, []),
          returnValue: _FakeDocumentReference_4()) as _i5.DocumentReference);
  @override
  _i18.Future<_i2.User?> getUser({String? uid}) =>
      (super.noSuchMethod(Invocation.method(#getUser, [], {#uid: uid}),
          returnValue: Future<_i2.User?>.value()) as _i18.Future<_i2.User?>);
  @override
  _i18.Future<List<_i19.UserFavPlaces>?>? getUserFavouritePlaces(
          {String? userId}) =>
      (super.noSuchMethod(
              Invocation.method(#getUserFavouritePlaces, [], {#userId: userId}))
          as _i18.Future<List<_i19.UserFavPlaces>?>?);
  @override
  _i18.Future<_i2.User?> getUserWithName({String? name}) => (super.noSuchMethod(
      Invocation.method(#getUserWithName, [], {#name: name}),
      returnValue: Future<_i2.User?>.value()) as _i18.Future<_i2.User?>);
  @override
  _i18.Future<_i3.UserStatistics> getUserSummaryStatistics({String? uid}) =>
      (super.noSuchMethod(
              Invocation.method(#getUserSummaryStatistics, [], {#uid: uid}),
              returnValue:
                  Future<_i3.UserStatistics>.value(_FakeUserStatistics_1()))
          as _i18.Future<_i3.UserStatistics>);
  @override
  _i18.Stream<_i3.UserStatistics> getUserSummaryStatisticsStream(
          {String? uid}) =>
      (super.noSuchMethod(
          Invocation.method(#getUserSummaryStatisticsStream, [], {#uid: uid}),
          returnValue:
              Stream<_i3.UserStatistics>.empty()) as _i18
          .Stream<_i3.UserStatistics>);
  @override
  _i18.Future<dynamic> updateUserData({_i2.User? user}) =>
      (super.noSuchMethod(Invocation.method(#updateUserData, [], {#user: user}),
          returnValue: Future<dynamic>.value()) as _i18.Future<dynamic>);
  @override
  _i18.Future<dynamic> addSponsorIdToUser({String? uid, String? sponsorId}) =>
      (super.noSuchMethod(
          Invocation.method(
              #addSponsorIdToUser, [], {#uid: uid, #sponsorId: sponsorId}),
          returnValue: Future<dynamic>.value()) as _i18.Future<dynamic>);
  @override
  _i18.Stream<_i2.User> getUserStream({String? uid}) =>
      (super.noSuchMethod(Invocation.method(#getUserStream, [], {#uid: uid}),
          returnValue: Stream<_i2.User>.empty()) as _i18.Stream<_i2.User>);
  @override
  _i18.Stream<List<_i2.User>> getExplorersDataStream({String? uid}) =>
      (super.noSuchMethod(
              Invocation.method(#getExplorersDataStream, [], {#uid: uid}),
              returnValue: Stream<List<_i2.User>>.empty())
          as _i18.Stream<List<_i2.User>>);
  @override
  _i18.Future<List<_i23.PublicUserInfo>> queryExplorers(
          {String? queryString}) =>
      (super.noSuchMethod(
          Invocation.method(#queryExplorers, [], {#queryString: queryString}),
          returnValue: Future<List<_i23.PublicUserInfo>>.value(
              <_i23.PublicUserInfo>[])) as _i18
          .Future<List<_i23.PublicUserInfo>>);
  @override
  _i18.Stream<List<_i24.MoneyTransfer>> getTransferDataStream(
          {_i25.MoneyTransferQueryConfig? config, String? uid}) =>
      (super.noSuchMethod(
              Invocation.method(
                  #getTransferDataStream, [], {#config: config, #uid: uid}),
              returnValue: Stream<List<_i24.MoneyTransfer>>.empty())
          as _i18.Stream<List<_i24.MoneyTransfer>>);
  @override
  _i10.Quest? getQuest({String? questId}) =>
      (super.noSuchMethod(Invocation.method(#getQuest, [], {#questId: questId}))
          as _i10.Quest?);
  @override
  _i18.Future<dynamic> pushFinishedQuest({_i12.ActivatedQuest? quest}) => (super
      .noSuchMethod(Invocation.method(#pushFinishedQuest, [], {#quest: quest}),
          returnValue: Future<dynamic>.value()) as _i18.Future<dynamic>);
  @override
  _i18.Future<_i13.AFKMarker?> getMarkerFromQrCodeId({String? qrCodeId}) =>
      (super.noSuchMethod(
          Invocation.method(#getMarkerFromQrCodeId, [], {#qrCodeId: qrCodeId}),
          returnValue:
              Future<_i13.AFKMarker?>.value()) as _i18.Future<_i13.AFKMarker?>);
  @override
  _i18.Future<List<_i10.Quest>> getQuestsWithStartMarkerId(
          {String? startMarkerId}) =>
      (super.noSuchMethod(
              Invocation.method(#getQuestsWithStartMarkerId, [],
                  {#startMarkerId: startMarkerId}),
              returnValue: Future<List<_i10.Quest>>.value(<_i10.Quest>[]))
          as _i18.Future<List<_i10.Quest>>);
  @override
  _i5.DocumentReference getUserStatisticsCollection({String? uid}) =>
      (super.noSuchMethod(
          Invocation.method(#getUserStatisticsCollection, [], {#uid: uid}),
          returnValue: _FakeDocumentReference_4()) as _i5.DocumentReference);
  @override
  _i5.DocumentReference getUserSummaryStatisticsDocument({String? uid}) =>
      (super.noSuchMethod(
          Invocation.method(#getUserSummaryStatisticsDocument, [], {#uid: uid}),
          returnValue: _FakeDocumentReference_4()) as _i5.DocumentReference);
  @override
  _i5.DocumentReference getUserFavouritePlacesDocument({String? uid}) =>
      (super.noSuchMethod(
          Invocation.method(#getUserFavouritePlacesDocument, [], {#uid: uid}),
          returnValue: _FakeDocumentReference_4()) as _i5.DocumentReference);
  @override
  _i5.DocumentReference getMarkersDocs({String? markerId}) =>
      (super.noSuchMethod(
          Invocation.method(#getMarkersDocs, [], {#markerId: markerId}),
          returnValue: _FakeDocumentReference_4()) as _i5.DocumentReference);
  @override
  String toString() => super.toString();
}

/// A class which mocks [EnvironmentService].
///
/// See the documentation for Mockito's code generation for more information.
class MockEnvironmentService extends _i1.Mock
    implements _i26.EnvironmentService {
  @override
  _i18.Future<dynamic> initialise() =>
      (super.noSuchMethod(Invocation.method(#initialise, []),
          returnValue: Future<dynamic>.value()) as _i18.Future<dynamic>);
  @override
  String getValue(String? key, {bool? verbose = false}) => (super.noSuchMethod(
      Invocation.method(#getValue, [key], {#verbose: verbose}),
      returnValue: '') as String);
  @override
  String toString() => super.toString();
}

/// A class which mocks [PlacesService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPlacesService extends _i1.Mock implements _i27.PlacesService {
  @override
  _i6.PlacesLocation get currentPosition =>
      (super.noSuchMethod(Invocation.getter(#currentPosition),
          returnValue: _FakePlacesLocation_5()) as _i6.PlacesLocation);
  @override
  void initialize({String? apiKey}) =>
      super.noSuchMethod(Invocation.method(#initialize, [], {#apiKey: apiKey}),
          returnValueForMissingStub: null);
  @override
  _i18.Future<List<_i6.PlacesAutoCompleteResult>> getAutoComplete(
          String? input) =>
      (super.noSuchMethod(Invocation.method(#getAutoComplete, [input]),
              returnValue: Future<List<_i6.PlacesAutoCompleteResult>>.value(
                  <_i6.PlacesAutoCompleteResult>[]))
          as _i18.Future<List<_i6.PlacesAutoCompleteResult>>);
  @override
  _i18.Future<_i6.PlacesDetails> getPlaceDetails(String? placeId) =>
      (super.noSuchMethod(Invocation.method(#getPlaceDetails, [placeId]),
              returnValue:
                  Future<_i6.PlacesDetails>.value(_FakePlacesDetails_6()))
          as _i18.Future<_i6.PlacesDetails>);
  @override
  _i18.Future<dynamic> getPlacesAtCurrentLocation() =>
      (super.noSuchMethod(Invocation.method(#getPlacesAtCurrentLocation, []),
          returnValue: Future<dynamic>.value()) as _i18.Future<dynamic>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [FlavorConfigProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockFlavorConfigProvider extends _i1.Mock
    implements _i28.FlavorConfigProvider {
  @override
  bool get allowDummyMarkerCollection =>
      (super.noSuchMethod(Invocation.getter(#allowDummyMarkerCollection),
          returnValue: false) as bool);
  @override
  set allowDummyMarkerCollection(bool? _allowDummyMarkerCollection) =>
      super.noSuchMethod(
          Invocation.setter(
              #allowDummyMarkerCollection, _allowDummyMarkerCollection),
          returnValueForMissingStub: null);
  @override
  bool get enableGPSVerification =>
      (super.noSuchMethod(Invocation.getter(#enableGPSVerification),
          returnValue: false) as bool);
  @override
  set enableGPSVerification(bool? _enableGPSVerification) => super.noSuchMethod(
      Invocation.setter(#enableGPSVerification, _enableGPSVerification),
      returnValueForMissingStub: null);
  @override
  _i28.Flavor get flavor => (super.noSuchMethod(Invocation.getter(#flavor),
      returnValue: _i28.Flavor.unknown) as _i28.Flavor);
  @override
  set flavor(_i28.Flavor? _flavor) =>
      super.noSuchMethod(Invocation.setter(#flavor, _flavor),
          returnValueForMissingStub: null);
  @override
  String get appName =>
      (super.noSuchMethod(Invocation.getter(#appName), returnValue: '')
          as String);
  @override
  String get authority =>
      (super.noSuchMethod(Invocation.getter(#authority), returnValue: '')
          as String);
  @override
  String get uripathprepend =>
      (super.noSuchMethod(Invocation.getter(#uripathprepend), returnValue: '')
          as String);
  @override
  void configure(_i28.Flavor? flavorIn) =>
      super.noSuchMethod(Invocation.method(#configure, [flavorIn]),
          returnValueForMissingStub: null);
  @override
  String getTestUserEmail(_i17.UserRole? role) =>
      (super.noSuchMethod(Invocation.method(#getTestUserEmail, [role]),
          returnValue: '') as String);
  @override
  String getTestUserPassword() =>
      (super.noSuchMethod(Invocation.method(#getTestUserPassword, []),
          returnValue: '') as String);
  @override
  String getTestUserId(_i17.UserRole? role) =>
      (super.noSuchMethod(Invocation.method(#getTestUserId, [role]),
          returnValue: '') as String);
  @override
  String toString() => super.toString();
}

/// A class which mocks [LocalStorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalStorageService extends _i1.Mock
    implements _i29.LocalStorageService {
  @override
  String get authTokenDataKey =>
      (super.noSuchMethod(Invocation.getter(#authTokenDataKey), returnValue: '')
          as String);
  @override
  set authTokenDataKey(String? _authTokenDataKey) => super.noSuchMethod(
      Invocation.setter(#authTokenDataKey, _authTokenDataKey),
      returnValueForMissingStub: null);
  @override
  _i18.Future<dynamic> saveToDisk({String? key, dynamic value}) =>
      (super.noSuchMethod(
          Invocation.method(#saveToDisk, [], {#key: key, #value: value}),
          returnValue: Future<dynamic>.value()) as _i18.Future<dynamic>);
  @override
  _i18.Future<dynamic> deleteFromDisk({String? key}) =>
      (super.noSuchMethod(Invocation.method(#deleteFromDisk, [], {#key: key}),
          returnValue: Future<dynamic>.value()) as _i18.Future<dynamic>);
  @override
  _i18.Future<dynamic> getFromDisk({String? key}) =>
      (super.noSuchMethod(Invocation.method(#getFromDisk, [], {#key: key}),
          returnValue: Future<dynamic>.value()) as _i18.Future<dynamic>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [FlutterSecureStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockFlutterSecureStorage extends _i1.Mock
    implements _i30.FlutterSecureStorage {
  @override
  _i18.Future<void> write(
          {String? key,
          String? value,
          _i30.IOSOptions? iOptions = _i30.IOSOptions.defaultOptions,
          _i30.AndroidOptions? aOptions,
          _i30.LinuxOptions? lOptions}) =>
      (super.noSuchMethod(
              Invocation.method(#write, [], {
                #key: key,
                #value: value,
                #iOptions: iOptions,
                #aOptions: aOptions,
                #lOptions: lOptions
              }),
              returnValue: Future<void>.value(),
              returnValueForMissingStub: Future<void>.value())
          as _i18.Future<void>);
  @override
  _i18.Future<String?> read(
          {String? key,
          _i30.IOSOptions? iOptions = _i30.IOSOptions.defaultOptions,
          _i30.AndroidOptions? aOptions,
          _i30.LinuxOptions? lOptions}) =>
      (super.noSuchMethod(
          Invocation.method(#read, [], {
            #key: key,
            #iOptions: iOptions,
            #aOptions: aOptions,
            #lOptions: lOptions
          }),
          returnValue: Future<String?>.value()) as _i18.Future<String?>);
  @override
  _i18.Future<bool> containsKey(
          {String? key,
          _i30.IOSOptions? iOptions = _i30.IOSOptions.defaultOptions,
          _i30.AndroidOptions? aOptions,
          _i30.LinuxOptions? lOptions}) =>
      (super.noSuchMethod(
          Invocation.method(#containsKey, [], {
            #key: key,
            #iOptions: iOptions,
            #aOptions: aOptions,
            #lOptions: lOptions
          }),
          returnValue: Future<bool>.value(false)) as _i18.Future<bool>);
  @override
  _i18.Future<void> delete(
          {String? key,
          _i30.IOSOptions? iOptions = _i30.IOSOptions.defaultOptions,
          _i30.AndroidOptions? aOptions,
          _i30.LinuxOptions? lOptions}) =>
      (super.noSuchMethod(
              Invocation.method(#delete, [], {
                #key: key,
                #iOptions: iOptions,
                #aOptions: aOptions,
                #lOptions: lOptions
              }),
              returnValue: Future<void>.value(),
              returnValueForMissingStub: Future<void>.value())
          as _i18.Future<void>);
  @override
  _i18.Future<Map<String, String>> readAll(
          {_i30.IOSOptions? iOptions = _i30.IOSOptions.defaultOptions,
          _i30.AndroidOptions? aOptions,
          _i30.LinuxOptions? lOptions}) =>
      (super.noSuchMethod(
              Invocation.method(#readAll, [], {
                #iOptions: iOptions,
                #aOptions: aOptions,
                #lOptions: lOptions
              }),
              returnValue:
                  Future<Map<String, String>>.value(<String, String>{}))
          as _i18.Future<Map<String, String>>);
  @override
  _i18.Future<void> deleteAll(
          {_i30.IOSOptions? iOptions = _i30.IOSOptions.defaultOptions,
          _i30.AndroidOptions? aOptions,
          _i30.LinuxOptions? lOptions}) =>
      (super.noSuchMethod(
              Invocation.method(#deleteAll, [], {
                #iOptions: iOptions,
                #aOptions: aOptions,
                #lOptions: lOptions
              }),
              returnValue: Future<void>.value(),
              returnValueForMissingStub: Future<void>.value())
          as _i18.Future<void>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [LayoutService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLayoutService extends _i1.Mock implements _i31.LayoutService {
  @override
  _i7.BehaviorSubject<bool> get showBottomNavBarSubject =>
      (super.noSuchMethod(Invocation.getter(#showBottomNavBarSubject),
              returnValue: _FakeBehaviorSubject_7<bool>())
          as _i7.BehaviorSubject<bool>);
  @override
  set showBottomNavBarSubject(
          _i7.BehaviorSubject<bool>? _showBottomNavBarSubject) =>
      super.noSuchMethod(
          Invocation.setter(#showBottomNavBarSubject, _showBottomNavBarSubject),
          returnValueForMissingStub: null);
  @override
  bool get showBottomNavBar =>
      (super.noSuchMethod(Invocation.getter(#showBottomNavBar),
          returnValue: false) as bool);
  @override
  void setShowBottomNavBar(bool? show) =>
      super.noSuchMethod(Invocation.method(#setShowBottomNavBar, [show]),
          returnValueForMissingStub: null);
  @override
  String toString() => super.toString();
}

/// A class which mocks [TransfersHistoryService].
///
/// See the documentation for Mockito's code generation for more information.
class MockTransfersHistoryService extends _i1.Mock
    implements _i32.TransfersHistoryService {
  @override
  Map<_i25.MoneyTransferQueryConfig, List<_i24.MoneyTransfer>>
      get latestTransfers => (super
              .noSuchMethod(Invocation.getter(#latestTransfers), returnValue: <
                  _i25.MoneyTransferQueryConfig, List<_i24.MoneyTransfer>>{})
          as Map<_i25.MoneyTransferQueryConfig, List<_i24.MoneyTransfer>>);
  @override
  set latestTransfers(
          Map<_i25.MoneyTransferQueryConfig, List<_i24.MoneyTransfer>>?
              _latestTransfers) =>
      super.noSuchMethod(Invocation.setter(#latestTransfers, _latestTransfers),
          returnValueForMissingStub: null);
  @override
  _i2.User get currentUser =>
      (super.noSuchMethod(Invocation.getter(#currentUser),
          returnValue: _FakeUser_0()) as _i2.User);
  @override
  _i18.Stream<List<_i24.MoneyTransfer>> getTransferDataStream(
          {_i25.MoneyTransferQueryConfig? config}) =>
      (super.noSuchMethod(
              Invocation.method(#getTransferDataStream, [], {#config: config}),
              returnValue: Stream<List<_i24.MoneyTransfer>>.empty())
          as _i18.Stream<List<_i24.MoneyTransfer>>);
  @override
  List<_i24.MoneyTransfer> getTransfers(
          {_i25.MoneyTransferQueryConfig? config}) =>
      (super.noSuchMethod(
          Invocation.method(#getTransfers, [], {#config: config}),
          returnValue: <_i24.MoneyTransfer>[]) as List<_i24.MoneyTransfer>);
  @override
  void addTransferDataListener(
          {_i25.MoneyTransferQueryConfig? config,
          _i18.Completer<void>? completer,
          void Function()? callback}) =>
      super.noSuchMethod(
          Invocation.method(#addTransferDataListener, [],
              {#config: config, #completer: completer, #callback: callback}),
          returnValueForMissingStub: null);
  @override
  void pauseTransferDataListener({_i25.MoneyTransferQueryConfig? config}) =>
      super.noSuchMethod(
          Invocation.method(#pauseTransferDataListener, [], {#config: config}),
          returnValueForMissingStub: null);
  @override
  void cancelTransferDataListener({_i25.MoneyTransferQueryConfig? config}) =>
      super.noSuchMethod(
          Invocation.method(#cancelTransferDataListener, [], {#config: config}),
          returnValueForMissingStub: null);
  @override
  List<_i24.MoneyTransfer> getMoneyTransfersWithUniqueSender(
          List<_i24.MoneyTransfer>? transfer) =>
      (super.noSuchMethod(
          Invocation.method(#getMoneyTransfersWithUniqueSender, [transfer]),
          returnValue: <_i24.MoneyTransfer>[]) as List<_i24.MoneyTransfer>);
  @override
  void clearData() => super.noSuchMethod(Invocation.method(#clearData, []),
      returnValueForMissingStub: null);
  @override
  String toString() => super.toString();
}

/// A class which mocks [GeolocationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockGeolocationService extends _i1.Mock
    implements _i33.GeolocationService {
  @override
  _i8.Position get getUserPosition =>
      (super.noSuchMethod(Invocation.getter(#getUserPosition),
          returnValue: _FakePosition_8()) as _i8.Position);
  @override
  _i9.CameraPosition initialCameraPosition() =>
      (super.noSuchMethod(Invocation.method(#initialCameraPosition, []),
          returnValue: _FakeCameraPosition_9()) as _i9.CameraPosition);
  @override
  _i18.Future<dynamic> getCurrentLocation() =>
      (super.noSuchMethod(Invocation.method(#getCurrentLocation, []),
          returnValue: Future<dynamic>.value()) as _i18.Future<dynamic>);
  @override
  _i18.Future<dynamic> setUserPosition({_i8.Position? position}) =>
      (super.noSuchMethod(
          Invocation.method(#setUserPosition, [], {#position: position}),
          returnValue: Future<dynamic>.value()) as _i18.Future<dynamic>);
  @override
  _i18.Future<bool> checkGeolocationAvailable() =>
      (super.noSuchMethod(Invocation.method(#checkGeolocationAvailable, []),
          returnValue: Future<bool>.value(false)) as _i18.Future<bool>);
  @override
  _i18.Future<bool> handlePermission() =>
      (super.noSuchMethod(Invocation.method(#handlePermission, []),
          returnValue: Future<bool>.value(false)) as _i18.Future<bool>);
  @override
  _i18.Future<List<_i34.Places>?> getPlaces() =>
      (super.noSuchMethod(Invocation.method(#getPlaces, []),
              returnValue: Future<List<_i34.Places>?>.value())
          as _i18.Future<List<_i34.Places>?>);
  @override
  _i18.Future<bool> isUserCloseby({double? lat, double? lon}) =>
      (super.noSuchMethod(
          Invocation.method(#isUserCloseby, [], {#lat: lat, #lon: lon}),
          returnValue: Future<bool>.value(false)) as _i18.Future<bool>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [QuestService].
///
/// See the documentation for Mockito's code generation for more information.
class MockQuestService extends _i1.Mock implements _i35.QuestService {
  @override
  _i7.BehaviorSubject<_i12.ActivatedQuest?> get activatedQuestSubject =>
      (super.noSuchMethod(Invocation.getter(#activatedQuestSubject),
              returnValue: _FakeBehaviorSubject_7<_i12.ActivatedQuest?>())
          as _i7.BehaviorSubject<_i12.ActivatedQuest?>);
  @override
  set activatedQuestSubject(
          _i7.BehaviorSubject<_i12.ActivatedQuest?>? _activatedQuestSubject) =>
      super.noSuchMethod(
          Invocation.setter(#activatedQuestSubject, _activatedQuestSubject),
          returnValueForMissingStub: null);
  @override
  bool get hasActiveQuest => (super
          .noSuchMethod(Invocation.getter(#hasActiveQuest), returnValue: false)
      as bool);
  @override
  _i10.Quest get getStartedQuest =>
      (super.noSuchMethod(Invocation.getter(#getStartedQuest),
          returnValue: _FakeQuest_10()) as _i10.Quest);
  @override
  _i18.Future<dynamic> startQuest({_i10.Quest? quest}) =>
      (super.noSuchMethod(Invocation.method(#startQuest, [], {#quest: quest}),
          returnValue: Future<dynamic>.value()) as _i18.Future<dynamic>);
  @override
  void setStartedQuest({_i10.Quest? startedQuest}) => super.noSuchMethod(
      Invocation.method(#setStartedQuest, [], {#startedQuest: startedQuest}),
      returnValueForMissingStub: null);
  @override
  _i18.Future<dynamic> evaluateAndFinishQuest() =>
      (super.noSuchMethod(Invocation.method(#evaluateAndFinishQuest, []),
          returnValue: Future<dynamic>.value()) as _i18.Future<dynamic>);
  @override
  _i18.Future<dynamic> finishQuest(
          {_i10.Quest? finishedQuest,
          int? numMarkersCollected,
          String? userId,
          String? timeElapse}) =>
      (super.noSuchMethod(
          Invocation.method(#finishQuest, [], {
            #finishedQuest: finishedQuest,
            #numMarkersCollected: numMarkersCollected,
            #userId: userId,
            #timeElapse: timeElapse
          }),
          returnValue: Future<dynamic>.value()) as _i18.Future<dynamic>);
  @override
  _i18.Future<dynamic> continueIncompleteQuest() =>
      (super.noSuchMethod(Invocation.method(#continueIncompleteQuest, []),
          returnValue: Future<dynamic>.value()) as _i18.Future<dynamic>);
  @override
  _i18.Future<dynamic> cancelIncompleteQuest() =>
      (super.noSuchMethod(Invocation.method(#cancelIncompleteQuest, []),
          returnValue: Future<dynamic>.value()) as _i18.Future<dynamic>);
  @override
  void evaluateQuest() =>
      super.noSuchMethod(Invocation.method(#evaluateQuest, []),
          returnValueForMissingStub: null);
  @override
  _i18.Future<dynamic> trackData(int? seconds) =>
      (super.noSuchMethod(Invocation.method(#trackData, [seconds]),
          returnValue: Future<dynamic>.value()) as _i18.Future<dynamic>);
  @override
  void updateCollectedMarkers({_i13.AFKMarker? marker}) => super.noSuchMethod(
      Invocation.method(#updateCollectedMarkers, [], {#marker: marker}),
      returnValueForMissingStub: null);
  @override
  bool isMarkerCollected({_i13.AFKMarker? marker}) => (super.noSuchMethod(
      Invocation.method(#isMarkerCollected, [], {#marker: marker}),
      returnValue: false) as bool);
  @override
  _i18.Future<_i11.QuestQRCodeScanResult> handleQrCodeScanEvent(
          {_i13.AFKMarker? marker}) =>
      (super.noSuchMethod(
              Invocation.method(#handleQrCodeScanEvent, [], {#marker: marker}),
              returnValue: Future<_i11.QuestQRCodeScanResult>.value(
                  _FakeQuestQRCodeScanResult_11()))
          as _i18.Future<_i11.QuestQRCodeScanResult>);
  @override
  _i18.Future<_i13.AFKMarker?> getMarkerFromQrCodeId({String? qrCodeId}) =>
      (super.noSuchMethod(
          Invocation.method(#getMarkerFromQrCodeId, [], {#qrCodeId: qrCodeId}),
          returnValue:
              Future<_i13.AFKMarker?>.value()) as _i18.Future<_i13.AFKMarker?>);
  @override
  void pushActivatedQuest(_i12.ActivatedQuest? quest) =>
      super.noSuchMethod(Invocation.method(#pushActivatedQuest, [quest]),
          returnValueForMissingStub: null);
  @override
  void removeActivatedQuest() =>
      super.noSuchMethod(Invocation.method(#removeActivatedQuest, []),
          returnValueForMissingStub: null);
  @override
  bool isMarkerInQuest({_i13.AFKMarker? marker}) => (super.noSuchMethod(
      Invocation.method(#isMarkerInQuest, [], {#marker: marker}),
      returnValue: false) as bool);
  @override
  _i18.Future<dynamic> getQuest({String? questId}) =>
      (super.noSuchMethod(Invocation.method(#getQuest, [], {#questId: questId}),
          returnValue: Future<dynamic>.value()) as _i18.Future<dynamic>);
  @override
  void updateTime(int? seconds) =>
      super.noSuchMethod(Invocation.method(#updateTime, [seconds]),
          returnValueForMissingStub: null);
  @override
  _i12.ActivatedQuest updateTimeOnQuest(
          _i12.ActivatedQuest? activatedQuest, int? seconds) =>
      (super.noSuchMethod(
          Invocation.method(#updateTimeOnQuest, [activatedQuest, seconds]),
          returnValue: _FakeActivatedQuest_12()) as _i12.ActivatedQuest);
  @override
  void disposeActivatedQuest() =>
      super.noSuchMethod(Invocation.method(#disposeActivatedQuest, []),
          returnValueForMissingStub: null);
  @override
  _i12.ActivatedQuest getActivatedQuest({_i10.Quest? quest}) => (super
      .noSuchMethod(Invocation.method(#getActivatedQuest, [], {#quest: quest}),
          returnValue: _FakeActivatedQuest_12()) as _i12.ActivatedQuest);
  @override
  String toString() => super.toString();
}

/// A class which mocks [StopWatchService].
///
/// See the documentation for Mockito's code generation for more information.
class MockStopWatchService extends _i1.Mock implements _i36.StopWatchService {
  @override
  bool get flag =>
      (super.noSuchMethod(Invocation.getter(#flag), returnValue: false)
          as bool);
  @override
  set flag(bool? _flag) => super.noSuchMethod(Invocation.setter(#flag, _flag),
      returnValueForMissingStub: null);
  @override
  set timerStream(_i18.Stream<int>? _timerStream) =>
      super.noSuchMethod(Invocation.setter(#timerStream, _timerStream),
          returnValueForMissingStub: null);
  @override
  String get getHours =>
      (super.noSuchMethod(Invocation.getter(#getHours), returnValue: '')
          as String);
  @override
  String get getMinutes =>
      (super.noSuchMethod(Invocation.getter(#getMinutes), returnValue: '')
          as String);
  @override
  String get getSeconds =>
      (super.noSuchMethod(Invocation.getter(#getSeconds), returnValue: '')
          as String);
  @override
  void startTimer() => super.noSuchMethod(Invocation.method(#startTimer, []),
      returnValueForMissingStub: null);
  @override
  void stopTimer() => super.noSuchMethod(Invocation.method(#stopTimer, []),
      returnValueForMissingStub: null);
  @override
  void resetTimer() => super.noSuchMethod(Invocation.method(#resetTimer, []),
      returnValueForMissingStub: null);
  @override
  int getSecondTime() =>
      (super.noSuchMethod(Invocation.method(#getSecondTime, []), returnValue: 0)
          as int);
  @override
  void listenToSecondTime({_i18.Future<dynamic> Function(int)? callback}) =>
      super.noSuchMethod(
          Invocation.method(#listenToSecondTime, [], {#callback: callback}),
          returnValueForMissingStub: null);
  @override
  void cancelListener() =>
      super.noSuchMethod(Invocation.method(#cancelListener, []),
          returnValueForMissingStub: null);
  @override
  void pauseListener() =>
      super.noSuchMethod(Invocation.method(#pauseListener, []),
          returnValueForMissingStub: null);
  @override
  void resumeListener() =>
      super.noSuchMethod(Invocation.method(#resumeListener, []),
          returnValueForMissingStub: null);
  @override
  void setHours({String? hours}) =>
      super.noSuchMethod(Invocation.method(#setHours, [], {#hours: hours}),
          returnValueForMissingStub: null);
  @override
  void setMinutes({String? minutes}) => super.noSuchMethod(
      Invocation.method(#setMinutes, [], {#minutes: minutes}),
      returnValueForMissingStub: null);
  @override
  void setSeconds({String? seconds}) => super.noSuchMethod(
      Invocation.method(#setSeconds, [], {#seconds: seconds}),
      returnValueForMissingStub: null);
  @override
  _i18.Stream<int> stopWatchStream() =>
      (super.noSuchMethod(Invocation.method(#stopWatchStream, []),
          returnValue: Stream<int>.empty()) as _i18.Stream<int>);
  @override
  void setTimerStreamSubscription(
          {_i18.StreamSubscription<int>? timerSubscription}) =>
      super.noSuchMethod(
          Invocation.method(#setTimerStreamSubscription, [],
              {#timerSubscription: timerSubscription}),
          returnValueForMissingStub: null);
  @override
  String toString() => super.toString();
}

/// A class which mocks [MarkerService].
///
/// See the documentation for Mockito's code generation for more information.
class MockMarkerService extends _i1.Mock implements _i37.MarkerService {
  @override
  List<_i13.AFKMarker> get getSetMarkers =>
      (super.noSuchMethod(Invocation.getter(#getSetMarkers),
          returnValue: <_i13.AFKMarker>[]) as List<_i13.AFKMarker>);
  @override
  _i18.Future<bool> isUserCloseby({_i13.AFKMarker? marker}) => (super
      .noSuchMethod(Invocation.method(#isUserCloseby, [], {#marker: marker}),
          returnValue: Future<bool>.value(false)) as _i18.Future<bool>);
  @override
  _i18.Future<void> createMarkers({_i13.AFKMarker? markers}) =>
      (super.noSuchMethod(
              Invocation.method(#createMarkers, [], {#markers: markers}),
              returnValue: Future<void>.value(),
              returnValueForMissingStub: Future<void>.value())
          as _i18.Future<void>);
  @override
  _i18.Future<List<_i13.AFKMarker>?> getQuestMarkers() =>
      (super.noSuchMethod(Invocation.method(#getQuestMarkers, []),
              returnValue: Future<List<_i13.AFKMarker>?>.value())
          as _i18.Future<List<_i13.AFKMarker>?>);
  @override
  _i18.Future<void> setQuestMarkers({List<_i13.AFKMarker>? markers}) =>
      (super.noSuchMethod(
              Invocation.method(#setQuestMarkers, [], {#markers: markers}),
              returnValue: Future<void>.value(),
              returnValueForMissingStub: Future<void>.value())
          as _i18.Future<void>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [QRCodeService].
///
/// See the documentation for Mockito's code generation for more information.
class MockQRCodeService extends _i1.Mock implements _i38.QRCodeService {
  @override
  _i13.AFKMarker getMarkerFromQrCodeString({String? qrCodeString}) =>
      (super.noSuchMethod(
          Invocation.method(
              #getMarkerFromQrCodeString, [], {#qrCodeString: qrCodeString}),
          returnValue: _FakeAFKMarker_13()) as _i13.AFKMarker);
  @override
  String getQrCodeStringFromMarker({_i13.AFKMarker? marker}) =>
      (super.noSuchMethod(
          Invocation.method(#getQrCodeStringFromMarker, [], {#marker: marker}),
          returnValue: '') as String);
  @override
  String toString() => super.toString();
}

/// A class which mocks [NavigationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNavigationService extends _i1.Mock implements _i39.NavigationService {
  @override
  String get previousRoute =>
      (super.noSuchMethod(Invocation.getter(#previousRoute), returnValue: '')
          as String);
  @override
  String get currentRoute =>
      (super.noSuchMethod(Invocation.getter(#currentRoute), returnValue: '')
          as String);
  @override
  _i40.GlobalKey<_i40.NavigatorState>? nestedNavigationKey(int? index) =>
      (super.noSuchMethod(Invocation.method(#nestedNavigationKey, [index]))
          as _i40.GlobalKey<_i40.NavigatorState>?);
  @override
  void config(
          {bool? enableLog,
          bool? defaultPopGesture,
          bool? defaultOpaqueRoute,
          Duration? defaultDurationTransition,
          bool? defaultGlobalState,
          String? defaultTransition}) =>
      super.noSuchMethod(
          Invocation.method(#config, [], {
            #enableLog: enableLog,
            #defaultPopGesture: defaultPopGesture,
            #defaultOpaqueRoute: defaultOpaqueRoute,
            #defaultDurationTransition: defaultDurationTransition,
            #defaultGlobalState: defaultGlobalState,
            #defaultTransition: defaultTransition
          }),
          returnValueForMissingStub: null);
  @override
  _i18.Future<T?>? navigateWithTransition<T>(_i40.Widget? page,
          {bool? opaque,
          String? transition = r'',
          Duration? duration,
          bool? popGesture,
          int? id,
          _i40.Curve? curve,
          _i39.Bindings? binding,
          bool? fullscreenDialog = false,
          bool? preventDuplicates = true,
          _i39.Transition? transitionClass}) =>
      (super.noSuchMethod(Invocation.method(#navigateWithTransition, [
        page
      ], {
        #opaque: opaque,
        #transition: transition,
        #duration: duration,
        #popGesture: popGesture,
        #id: id,
        #curve: curve,
        #binding: binding,
        #fullscreenDialog: fullscreenDialog,
        #preventDuplicates: preventDuplicates,
        #transitionClass: transitionClass
      })) as _i18.Future<T?>?);
  @override
  _i18.Future<T?>? replaceWithTransition<T>(_i40.Widget? page,
          {bool? opaque,
          String? transition = r'',
          Duration? duration,
          bool? popGesture,
          int? id,
          _i40.Curve? curve,
          _i39.Bindings? binding,
          bool? fullscreenDialog = false,
          bool? preventDuplicates = true,
          _i39.Transition? transitionClass}) =>
      (super.noSuchMethod(Invocation.method(#replaceWithTransition, [
        page
      ], {
        #opaque: opaque,
        #transition: transition,
        #duration: duration,
        #popGesture: popGesture,
        #id: id,
        #curve: curve,
        #binding: binding,
        #fullscreenDialog: fullscreenDialog,
        #preventDuplicates: preventDuplicates,
        #transitionClass: transitionClass
      })) as _i18.Future<T?>?);
  @override
  bool back<T>({T? result, int? id}) => (super.noSuchMethod(
      Invocation.method(#back, [], {#result: result, #id: id}),
      returnValue: false) as bool);
  @override
  void popUntil(_i40.RoutePredicate? predicate) =>
      super.noSuchMethod(Invocation.method(#popUntil, [predicate]),
          returnValueForMissingStub: null);
  @override
  void popRepeated(int? popTimes) =>
      super.noSuchMethod(Invocation.method(#popRepeated, [popTimes]),
          returnValueForMissingStub: null);
  @override
  _i18.Future<T?>? navigateTo<T>(String? routeName,
          {dynamic arguments,
          int? id,
          bool? preventDuplicates = true,
          Map<String, String>? parameters}) =>
      (super.noSuchMethod(Invocation.method(#navigateTo, [
        routeName
      ], {
        #arguments: arguments,
        #id: id,
        #preventDuplicates: preventDuplicates,
        #parameters: parameters
      })) as _i18.Future<T?>?);
  @override
  _i18.Future<T?>? navigateToView<T>(_i40.Widget? view,
          {dynamic arguments,
          int? id,
          bool? opaque,
          _i40.Curve? curve,
          _i39.Bindings? binding,
          Duration? duration,
          bool? fullscreenDialog = false,
          bool? popGesture,
          bool? preventDuplicates = true,
          _i39.Transition? transition}) =>
      (super.noSuchMethod(Invocation.method(#navigateToView, [
        view
      ], {
        #arguments: arguments,
        #id: id,
        #opaque: opaque,
        #curve: curve,
        #binding: binding,
        #duration: duration,
        #fullscreenDialog: fullscreenDialog,
        #popGesture: popGesture,
        #preventDuplicates: preventDuplicates,
        #transition: transition
      })) as _i18.Future<T?>?);
  @override
  _i18.Future<T?>? replaceWith<T>(String? routeName,
          {dynamic arguments,
          int? id,
          bool? preventDuplicates = true,
          Map<String, String>? parameters}) =>
      (super.noSuchMethod(Invocation.method(#replaceWith, [
        routeName
      ], {
        #arguments: arguments,
        #id: id,
        #preventDuplicates: preventDuplicates,
        #parameters: parameters
      })) as _i18.Future<T?>?);
  @override
  _i18.Future<T?>? clearStackAndShow<T>(String? routeName,
          {dynamic arguments, int? id, Map<String, String>? parameters}) =>
      (super.noSuchMethod(Invocation.method(#clearStackAndShow, [
        routeName
      ], {
        #arguments: arguments,
        #id: id,
        #parameters: parameters
      })) as _i18.Future<T?>?);
  @override
  _i18.Future<T?>? clearTillFirstAndShow<T>(String? routeName,
          {dynamic arguments,
          int? id,
          bool? preventDuplicates = true,
          Map<String, String>? parameters}) =>
      (super.noSuchMethod(Invocation.method(#clearTillFirstAndShow, [
        routeName
      ], {
        #arguments: arguments,
        #id: id,
        #preventDuplicates: preventDuplicates,
        #parameters: parameters
      })) as _i18.Future<T?>?);
  @override
  _i18.Future<T?>? clearTillFirstAndShowView<T>(_i40.Widget? view,
          {dynamic arguments, int? id}) =>
      (super.noSuchMethod(Invocation.method(#clearTillFirstAndShowView, [view],
          {#arguments: arguments, #id: id})) as _i18.Future<T?>?);
  @override
  _i18.Future<T?>? pushNamedAndRemoveUntil<T>(String? routeName,
          {_i40.RoutePredicate? predicate, dynamic arguments, int? id}) =>
      (super.noSuchMethod(Invocation.method(#pushNamedAndRemoveUntil, [
        routeName
      ], {
        #predicate: predicate,
        #arguments: arguments,
        #id: id
      })) as _i18.Future<T?>?);
  @override
  String toString() => super.toString();
}

/// A class which mocks [SnackbarService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSnackbarService extends _i1.Mock implements _i39.SnackbarService {
  @override
  void registerSnackbarConfig(_i39.SnackbarConfig? config) =>
      super.noSuchMethod(Invocation.method(#registerSnackbarConfig, [config]),
          returnValueForMissingStub: null);
  @override
  void registerCustomSnackbarconfig(
          {dynamic customData, _i39.SnackbarConfig? config}) =>
      super.noSuchMethod(
          Invocation.method(#registerCustomSnackbarconfig, [],
              {#customData: customData, #config: config}),
          returnValueForMissingStub: null);
  @override
  void registerCustomMainButtonBuilder(
          {dynamic variant,
          _i40.Widget Function(String?, Function?)? builder}) =>
      super.noSuchMethod(
          Invocation.method(#registerCustomMainButtonBuilder, [],
              {#variant: variant, #builder: builder}),
          returnValueForMissingStub: null);
  @override
  void registerCustomSnackbarConfig(
          {dynamic variant,
          _i39.SnackbarConfig? config,
          _i39.SnackbarConfig Function()? configBuilder}) =>
      super.noSuchMethod(
          Invocation.method(#registerCustomSnackbarConfig, [], {
            #variant: variant,
            #config: config,
            #configBuilder: configBuilder
          }),
          returnValueForMissingStub: null);
  @override
  void showSnackbar(
          {String? title = r'',
          String? message,
          dynamic Function(dynamic)? onTap,
          Duration? duration = const Duration(seconds: 3),
          String? mainButtonTitle,
          void Function()? onMainButtonTapped}) =>
      super.noSuchMethod(
          Invocation.method(#showSnackbar, [], {
            #title: title,
            #message: message,
            #onTap: onTap,
            #duration: duration,
            #mainButtonTitle: mainButtonTitle,
            #onMainButtonTapped: onMainButtonTapped
          }),
          returnValueForMissingStub: null);
  @override
  _i18.Future<dynamic>? showCustomSnackBar(
          {String? message,
          dynamic customData,
          dynamic variant,
          String? title,
          String? mainButtonTitle,
          void Function()? onMainButtonTapped,
          Function? onTap,
          Duration? duration = const Duration(seconds: 1)}) =>
      (super.noSuchMethod(Invocation.method(#showCustomSnackBar, [], {
        #message: message,
        #customData: customData,
        #variant: variant,
        #title: title,
        #mainButtonTitle: mainButtonTitle,
        #onMainButtonTapped: onMainButtonTapped,
        #onTap: onTap,
        #duration: duration
      })) as _i18.Future<dynamic>?);
  @override
  String toString() => super.toString();
}

/// A class which mocks [DialogService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDialogService extends _i1.Mock implements _i39.DialogService {
  @override
  void registerCustomDialogBuilders(
          Map<dynamic, _i39.DialogBuilder>? builders) =>
      super.noSuchMethod(
          Invocation.method(#registerCustomDialogBuilders, [builders]),
          returnValueForMissingStub: null);
  @override
  void registerCustomDialogBuilder(
          {dynamic variant,
          _i40.Widget Function(_i40.BuildContext, _i39.DialogRequest<dynamic>,
                  dynamic Function(_i39.DialogResponse<dynamic>))?
              builder}) =>
      super.noSuchMethod(
          Invocation.method(#registerCustomDialogBuilder, [],
              {#variant: variant, #builder: builder}),
          returnValueForMissingStub: null);
  @override
  _i18.Future<_i39.DialogResponse<dynamic>?> showDialog(
          {String? title,
          String? description,
          String? cancelTitle,
          _i41.Color? cancelTitleColor,
          String? buttonTitle = r'Ok',
          _i41.Color? buttonTitleColor,
          bool? barrierDismissible = false,
          _i39.DialogPlatform? dialogPlatform}) =>
      (super.noSuchMethod(
              Invocation.method(#showDialog, [], {
                #title: title,
                #description: description,
                #cancelTitle: cancelTitle,
                #cancelTitleColor: cancelTitleColor,
                #buttonTitle: buttonTitle,
                #buttonTitleColor: buttonTitleColor,
                #barrierDismissible: barrierDismissible,
                #dialogPlatform: dialogPlatform
              }),
              returnValue: Future<_i39.DialogResponse<dynamic>?>.value())
          as _i18.Future<_i39.DialogResponse<dynamic>?>);
  @override
  _i18.Future<_i39.DialogResponse<T>?> showCustomDialog<T, R>(
          {dynamic variant,
          String? title,
          String? description,
          bool? hasImage = false,
          String? imageUrl,
          bool? showIconInMainButton = false,
          String? mainButtonTitle,
          bool? showIconInSecondaryButton = false,
          String? secondaryButtonTitle,
          bool? showIconInAdditionalButton = false,
          String? additionalButtonTitle,
          bool? takesInput = false,
          _i41.Color? barrierColor = const _i41.Color(2315255808),
          bool? barrierDismissible = false,
          String? barrierLabel = r'',
          dynamic customData,
          R? data}) =>
      (super.noSuchMethod(
              Invocation.method(#showCustomDialog, [], {
                #variant: variant,
                #title: title,
                #description: description,
                #hasImage: hasImage,
                #imageUrl: imageUrl,
                #showIconInMainButton: showIconInMainButton,
                #mainButtonTitle: mainButtonTitle,
                #showIconInSecondaryButton: showIconInSecondaryButton,
                #secondaryButtonTitle: secondaryButtonTitle,
                #showIconInAdditionalButton: showIconInAdditionalButton,
                #additionalButtonTitle: additionalButtonTitle,
                #takesInput: takesInput,
                #barrierColor: barrierColor,
                #barrierDismissible: barrierDismissible,
                #barrierLabel: barrierLabel,
                #customData: customData,
                #data: data
              }),
              returnValue: Future<_i39.DialogResponse<T>?>.value())
          as _i18.Future<_i39.DialogResponse<T>?>);
  @override
  _i18.Future<_i39.DialogResponse<dynamic>?> showConfirmationDialog(
          {String? title,
          String? description,
          String? cancelTitle = r'Cancel',
          String? confirmationTitle = r'Ok',
          bool? barrierDismissible = false,
          _i39.DialogPlatform? dialogPlatform}) =>
      (super.noSuchMethod(
              Invocation.method(#showConfirmationDialog, [], {
                #title: title,
                #description: description,
                #cancelTitle: cancelTitle,
                #confirmationTitle: confirmationTitle,
                #barrierDismissible: barrierDismissible,
                #dialogPlatform: dialogPlatform
              }),
              returnValue: Future<_i39.DialogResponse<dynamic>?>.value())
          as _i18.Future<_i39.DialogResponse<dynamic>?>);
  @override
  void completeDialog(_i39.DialogResponse<dynamic>? response) =>
      super.noSuchMethod(Invocation.method(#completeDialog, [response]),
          returnValueForMissingStub: null);
  @override
  String toString() => super.toString();
}

/// A class which mocks [FirebaseAuthenticationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirebaseAuthenticationService extends _i1.Mock
    implements _i15.FirebaseAuthenticationService {
  @override
  _i14.FirebaseAuth get firebaseAuth =>
      (super.noSuchMethod(Invocation.getter(#firebaseAuth),
          returnValue: _FakeFirebaseAuth_14()) as _i14.FirebaseAuth);
  @override
  bool get hasUser =>
      (super.noSuchMethod(Invocation.getter(#hasUser), returnValue: false)
          as bool);
  @override
  _i18.Stream<_i14.User?> get authStateChanges =>
      (super.noSuchMethod(Invocation.getter(#authStateChanges),
          returnValue: Stream<_i14.User?>.empty()) as _i18.Stream<_i14.User?>);
  @override
  _i18.Future<bool> emailExists(String? email) =>
      (super.noSuchMethod(Invocation.method(#emailExists, [email]),
          returnValue: Future<bool>.value(false)) as _i18.Future<bool>);
  @override
  _i18.Future<_i15.FirebaseAuthenticationResult> signInWithGoogle() =>
      (super.noSuchMethod(Invocation.method(#signInWithGoogle, []),
              returnValue: Future<_i15.FirebaseAuthenticationResult>.value(
                  _FakeFirebaseAuthenticationResult_15()))
          as _i18.Future<_i15.FirebaseAuthenticationResult>);
  @override
  _i18.Future<bool> isAppleSignInAvailable() =>
      (super.noSuchMethod(Invocation.method(#isAppleSignInAvailable, []),
          returnValue: Future<bool>.value(false)) as _i18.Future<bool>);
  @override
  _i18.Future<_i15.FirebaseAuthenticationResult> signInWithApple(
          {String? appleRedirectUri, String? appleClientId}) =>
      (super.noSuchMethod(
              Invocation.method(#signInWithApple, [], {
                #appleRedirectUri: appleRedirectUri,
                #appleClientId: appleClientId
              }),
              returnValue: Future<_i15.FirebaseAuthenticationResult>.value(
                  _FakeFirebaseAuthenticationResult_15()))
          as _i18.Future<_i15.FirebaseAuthenticationResult>);
  @override
  _i18.Future<_i15.FirebaseAuthenticationResult> loginAnonymously() =>
      (super.noSuchMethod(Invocation.method(#loginAnonymously, []),
              returnValue: Future<_i15.FirebaseAuthenticationResult>.value(
                  _FakeFirebaseAuthenticationResult_15()))
          as _i18.Future<_i15.FirebaseAuthenticationResult>);
  @override
  _i18.Future<_i15.FirebaseAuthenticationResult> loginWithEmail(
          {String? email, String? password}) =>
      (super.noSuchMethod(
              Invocation.method(
                  #loginWithEmail, [], {#email: email, #password: password}),
              returnValue: Future<_i15.FirebaseAuthenticationResult>.value(
                  _FakeFirebaseAuthenticationResult_15()))
          as _i18.Future<_i15.FirebaseAuthenticationResult>);
  @override
  _i18.Future<_i15.FirebaseAuthenticationResult> createAccountWithEmail(
          {String? email, String? password}) =>
      (super.noSuchMethod(
              Invocation.method(#createAccountWithEmail, [],
                  {#email: email, #password: password}),
              returnValue: Future<_i15.FirebaseAuthenticationResult>.value(
                  _FakeFirebaseAuthenticationResult_15()))
          as _i18.Future<_i15.FirebaseAuthenticationResult>);
  @override
  _i18.Future<dynamic> logout() =>
      (super.noSuchMethod(Invocation.method(#logout, []),
          returnValue: Future<dynamic>.value()) as _i18.Future<dynamic>);
  @override
  _i18.Future<dynamic> sendResetPasswordLink(String? email) =>
      (super.noSuchMethod(Invocation.method(#sendResetPasswordLink, [email]),
          returnValue: Future<dynamic>.value()) as _i18.Future<dynamic>);
  @override
  _i18.Future<dynamic> validatePassword(String? password) =>
      (super.noSuchMethod(Invocation.method(#validatePassword, [password]),
          returnValue: Future<dynamic>.value()) as _i18.Future<dynamic>);
  @override
  _i18.Future<dynamic> updatePassword(String? password) =>
      (super.noSuchMethod(Invocation.method(#updatePassword, [password]),
          returnValue: Future<dynamic>.value()) as _i18.Future<dynamic>);
  @override
  _i18.Future<dynamic> updateEmail(String? email) =>
      (super.noSuchMethod(Invocation.method(#updateEmail, [email]),
          returnValue: Future<dynamic>.value()) as _i18.Future<dynamic>);
  @override
  String generateNonce([int? length = 32]) =>
      (super.noSuchMethod(Invocation.method(#generateNonce, [length]),
          returnValue: '') as String);
  @override
  String sha256ofString(String? input) =>
      (super.noSuchMethod(Invocation.method(#sha256ofString, [input]),
          returnValue: '') as String);
  @override
  String toString() => super.toString();
}
